const territories = [
  {"name": "Laklanõ", "slug": "laklano"},
  {
    "name": "Seminole Tribe of Florida (Brighton Reservation)",
    "slug": "seminole-tribe-of-florida-brighton-reservation"
  },
  {"name": "Charrúa", "slug": "charruas"},
  {"name": "Kokomini", "slug": "kokomini"},
  {"name": "Chilula", "slug": "chilula"},
  {"name": "Eastern Shoshone", "slug": "eastern-shoshone"},
  {"name": "Runixa Ngiigua (Chocho)", "slug": "popoluca-chocho"},
  {"name": "Margany", "slug": "margany"},
  {"name": "Nonuya", "slug": "nonuya"},
  {
    "name": "Ngāti Mutunga o Wharekauri (Chatham Islands)",
    "slug": "ngati-mutunga-o-wharekauri-chatham-islands"
  },
  {"name": "Bïde", "slug": "bide"},
  {"name": "Gunbalang", "slug": "gunbalang"},
  {"name": "Atsugewi", "slug": "atsugewi"},
  {"name": "Cape Fear", "slug": "cape-fear"},
  {"name": "Chiricahua Apache", "slug": "chiricahua-apache"},
  {"name": "Pamoari", "slug": "pamoari"},
  {"name": "Assiniboine", "slug": "assiniboine"},
  {"name": "Secwepemcúl'ecw (Secwépemc)", "slug": "secwepemc-secwepemcul-ewc"},
  {"name": "Kriol", "slug": "kriol"},
  {"name": "Mexicanero (Nahuas)", "slug": "mexicanero-nahuatl"},
  {"name": "Andoa", "slug": "andoa"},
  {"name": "Mosetén", "slug": "moseten"},
  {"name": "Queets", "slug": "queets"},
  {"name": "Nungali", "slug": "nungali"},
  {"name": "Uspantec", "slug": "uspantec"},
  {"name": "Entiat", "slug": "entiat"},
  {"name": "Nuwhaha", "slug": "nuwhaha"},
  {"name": "Wangan", "slug": "wangan"},
  {"name": "Quuiich (Lower Umpqua)", "slug": "quuiich-lower-umpqua"},
  {"name": "Ga", "slug": "ga"},
  {"name": "Ngalakan", "slug": "ngalakan"},
  {"name": "E'ñepá", "slug": "enepa"},
  {"name": "Mirning", "slug": "mirning"},
  {"name": "Emberá Chamí", "slug": "embera-chami"},
  {"name": "Mayi-Kutuna", "slug": "mayi-kutuna"},
  {"name": "Yindjibarndi", "slug": "yindjibarndi"},
  {"name": "Attiwonderonk (Neutral)", "slug": "attiwonderonk-neutral"},
  {"name": "Arabana", "slug": "arabana"},
  {"name": "Yoreme (Mayo)", "slug": "mayo"},
  {"name": "Nunggubuyu", "slug": "nunggubuyu"},
  {"name": "Chamicuro", "slug": "chamicuro"},
  {"name": "Yagán", "slug": "yagan"},
  {"name": "Sharanahua", "slug": "sharanahua"},
  {"name": "Kiliwa", "slug": "kiliwa"},
  {"name": "Guarijío/Guarijó", "slug": "guarijio"},
  {"name": "Boonwurrung", "slug": "bonwurrung"},
  {"name": "Sirionó", "slug": "siriono"},
  {"name": "Wyandotte (Oklahoma)", "slug": "wyandotte-oklahoma"},
  {"name": "Winaq Qo’ (Mam)", "slug": "mam"},
  {"name": "Kichwa del Río Pastaza", "slug": "kichwa-del-rio-pastaza"},
  {"name": "Tamaulipeco tribes", "slug": "tamaulipeco-tribes"},
  {"name": "Tzjon Non/ Tzo'tyio (Amuzgo)", "slug": "amuzgo"},
  {"name": "Günün a atük (Günün a küna)", "slug": "gunun-a-atuk-gunun-a-kuna"},
  {"name": "Yanda", "slug": "yanda"},
  {"name": "Mandandanji", "slug": "mandandanji"},
  {
    "name": "Ngāti Kahungunu ki Heretaunga Tamatea",
    "slug": "ngati-kahungunu-ki-heretaunga-tamatea"
  },
  {"name": "Bindjali", "slug": "bindjali"},
  {"name": "Wakuenai/Walimanai (Kuripako)", "slug": "kurripako"},
  {"name": "Tepehua", "slug": "tepehua"},
  {"name": "Emberá", "slug": "embera-3"},
  {"name": "Maniapoto", "slug": "maniapoto"},
  {"name": "Bilinara", "slug": "bilinara"},
  {"name": "Ngāi Tai ki Tāmaki", "slug": "ngai-tai-ki-tamaki"},
  {"name": "Lardil", "slug": "lardil"},
  {"name": "Ngāti Te Ata", "slug": "ngati-te-ata"},
  {"name": "White River-Kluane", "slug": "white-river-kluane"},
  {"name": "Ngāti Pūkenga ki Waiau", "slug": "ngati-pukenga-ki-waiau"},
  {"name": "Siginygmit (Sireniki) Yupik", "slug": "siginygmit-sireniki-yupik"},
  {"name": "Wabanaki (Dawnland Confederacy)", "slug": "wabanaki-confederacy"},
  {"name": "Pacaxes", "slug": "pacaxes"},
  {"name": "Tjerratj", "slug": "tjerratj"},
  {"name": "Ucluelet", "slug": "ucluelet"},
  {"name": "Karajarri", "slug": "karajarri"},
  {"name": "Modoc", "slug": "modoc"},
  {"name": "Darumbal", "slug": "darumbal"},
  {"name": "Tekohá (Guarani)", "slug": "guarani"},
  {"name": "Limilngan", "slug": "limilngan"},
  {"name": "Hesquiaht", "slug": "hesquiaht"},
  {"name": "Havasu Baaja (Havasupai)", "slug": "havasupai"},
  {"name": "Kalaamaya", "slug": "kalaamaya"},
  {"name": "Muralag", "slug": "muralag"},
  {"name": "Shawi", "slug": "shawi"},
  {"name": "Nuxalk", "slug": "nuxalk"},
  {"name": "Gugu-Badhun", "slug": "gugu-badhun"},
  {"name": "Matecumbe", "slug": "matecumbe"},
  {"name": "Killaka Asanajaqi", "slug": "killaka-asanajaqi"},
  {"name": "Huu-ay-aht", "slug": "huu-ay-aht"},
  {"name": "Moraughtacund", "slug": "moraughtacund"},
  {"name": "Ainu", "slug": "ainu"},
  {"name": "Kwikwetlem", "slug": "kwikwetlem"},
  {"name": "Ikolen", "slug": "ikolen"},
  {"name": "Eperara Siapidara", "slug": "eperara-siapidara"},
  {"name": "Kakataibo", "slug": "kakataibo"},
  {"name": "Kathlamet", "slug": "kathlamet"},
  {"name": "Ngāi Tai ki Tāmaki", "slug": "ngai-tai-ki-tamaki"},
  {"name": "Angaité", "slug": "angaite"},
  {"name": "Wudjari", "slug": "wudjari"},
  {"name": "Natabuela", "slug": "natabuela"},
  {"name": "Nadleh Whut'en", "slug": "nadleh-whuten"},
  {"name": "Yalarrnga", "slug": "yalarrnga"},
  {"name": "Waiwai", "slug": "waiwai"},
  {"name": "Ngāti Tamaoho", "slug": "ngati-tamaoho"},
  {"name": "Ashaninka", "slug": "ashaninka"},
  {"name": "San Carlos Apache", "slug": "san-carlos-apache"},
  {"name": "Teslin Tlingit Council (BC)", "slug": "teslin-tlingit-council"},
  {"name": "Sauk Suiattle", "slug": "sauk-suiattle"},
  {"name": "Penobscot", "slug": "penobscot-2"},
  {"name": "[Gáuigú (Kiowa)", "slug": "kiowa"},
  {"name": "Northeastern Pomo", "slug": "northeastern-pomo"},
  {"name": "Karkin", "slug": "karkin"},
  {"name": "Ayahuacas", "slug": "ayahuacas"},
  {"name": "Mudburra", "slug": "mudburra"},
  {"name": "Mi'kma'ki", "slug": "mi-kmaq"},
  {"name": "Kaingang", "slug": "kaingang"},
  {"name": "Kawashkar", "slug": "kawashkar"},
  {"name": "Ngāti Maru (Hauraki)", "slug": "ngati-maru-hauraki"},
  {"name": "Matinecock", "slug": "matinecock"},
  {"name": "Yitha Yitha", "slug": "yitha-yitha"},
  {"name": "Passamaquoddy", "slug": "passamaquoddy"},
  {"name": "Mbeiwum", "slug": "mbeiwum"},
  {"name": "Magüta/Ticuna", "slug": "maguta-ticuna"},
  {
    "name": "səl̓ilwətaɁɬ təməxʷ (Tsleil-Waututh)",
    "slug": "tsleil-waututh-səl̓ilwətaɂɬ"
  },
  {"name": "Aucocisco", "slug": "aucocisco"},
  {"name": "Zoró/Pangyjej", "slug": "zoro-pangyjej"},
  {"name": "Goreng", "slug": "goreng"},
  {"name": "Kantaruré", "slug": "kantarure"},
  {"name": "Bostos", "slug": "bostos"},
  {"name": "Achagua", "slug": "achagua"},
  {"name": "Lingít Aaní (Tlingit)", "slug": "tlingit"},
  {"name": "Gunwinggu", "slug": "gunwinggu"},
  {"name": "Toogee", "slug": "toogee"},
  {"name": "Mayangna", "slug": "mayangna"},
  {"name": "Canela Ramkokamekrá", "slug": "canela-ramkokamekra"},
  {"name": "Wiradjuri", "slug": "wiradjuri"},
  {"name": "Julimes", "slug": "julimes"},
  {"name": "Wulgurukaba", "slug": "wulgurukaba"},
  {"name": "Chimacum", "slug": "chimacum"},
  {"name": "We Wai Kai", "slug": "we-wai-kai"},
  {"name": "Awá", "slug": "awa-2"},
  {"name": "Arrernte", "slug": "arrernte"},
  {"name": "Yadhaigana", "slug": "yadhaigana"},
  {"name": "Kuuku-ya’u", "slug": "kuuku-yau"},
  {"name": "Mardu", "slug": "mardu"},
  {"name": "Xakriabá", "slug": "xakriaba"},
  {"name": "Nukini", "slug": "nukini"},
  {"name": "Enenlhet-Toba", "slug": "enenlhet-toba"},
  {"name": "Yoko T’aan (Chontal)", "slug": "chontal-de-tabasco"},
  {"name": "Konbudj", "slug": "konbudj"},
  {"name": "Mánekenk/Haush", "slug": "manekenk-haush"},
  {"name": "Manahoac", "slug": "manahoac"},
  {
    "name": "Whanganui Land Settlement (Lower Whanganui)",
    "slug": "whanganui-land-settlement-lower-whanganui"
  },
  {"name": "Gayiri", "slug": "gayiri"},
  {"name": "Sinkyone", "slug": "sinkyone"},
  {"name": "Kamëntsá", "slug": "kamentsa"},
  {"name": "Tastil", "slug": "tastil"},
  {"name": "Odǫhwęja:deˀ (Cayuga)", "slug": "cayuga"},
  {"name": "Yinggarda", "slug": "yinggarda"},
  {"name": "Chapra", "slug": "chapra"},
  {"name": "Fernandeño Tataviam", "slug": "fernandeno-tataviam"},
  {"name": "Ocloya", "slug": "ocloya"},
  {
    "name": "Kelly Lake Metis Settlement Society",
    "slug": "kelly-lake-metis-settlement-society"
  },
  {"name": "Nunatsiavut", "slug": "nunatsiavut"},
  {"name": "Western Nehântick", "slug": "western-nehantick"},
  {"name": "Ngāti Pikiao", "slug": "ngati-pikiao"},
  {"name": "Nansemond", "slug": "nansemond-2"},
  {"name": "Waxhaw", "slug": "waxhaw"},
  {"name": "Puyallup", "slug": "puyallup"},
  {"name": "Nitaskinan (Atikamekw / Nehirowisi Aski)", "slug": "atikamekw"},
  {"name": "Me-Wuk (Coast Miwok)", "slug": "coast-miwok"},
  {"name": "Moqoit", "slug": "moqoit"},
  {"name": "Jamamadi", "slug": "jamamadi"},
  {"name": "Yidinjdji", "slug": "yidinjdji"},
  {"name": "Ngāti Maru (Hauraki)", "slug": "ngati-maru-hauraki"},
  {"name": "Ngāti Hako", "slug": "ngati-hako"},
  {"name": "Uru", "slug": "uru"},
  {"name": "Yuwi", "slug": "yuwi"},
  {"name": "Shíshálh", "slug": "shshlh"},
  {"name": "Ngarinyin", "slug": "ngarinyin"},
  {"name": "Luckiamute", "slug": "luckiamute"},
  {"name": "Tūhourangi", "slug": "tuhourangi"},
  {"name": "Inughuit Nunaat", "slug": "avanersuaq"},
  {"name": "Peramangk", "slug": "peramangk"},
  {"name": "Ijku (Arhuaco)", "slug": "ijku-arhuaco"},
  {"name": "Nanrantsouak", "slug": "nanrantsouak"},
  {"name": "Garífuna", "slug": "garifuna"},
  {"name": "Wangkamana", "slug": "wangkamana"},
  {"name": "Kichwa (Amazónico)", "slug": "kichwa-amazonico"},
  {"name": "Kambeba/Omagua", "slug": "kambeba-omagua"},
  {"name": "Limuw", "slug": "limuw"},
  {"name": "Kogui/Kaggabba", "slug": "kogui-kaggabba"},
  {"name": "Tutelo", "slug": "tutelo-2"},
  {"name": "Kallawaya", "slug": "kallawaya"},
  {
    "name": "Tagé Cho Hudän (Little Salmon/Carmacks)",
    "slug": "little-salmon-carmacks"
  },
  {"name": "Atakapa-Ishak", "slug": "atakapa-2"},
  {"name": "Ngāti Manuhiri", "slug": "ngati-manuhiri"},
  {"name": "Jococobas", "slug": "jococobas"},
  {"name": "Doeg", "slug": "doeg"},
  {"name": "Amahuaca", "slug": "amahuaca"},
  {"name": "Bodéwadmiakiwen (Potawatomi)", "slug": "potawatomi"},
  {"name": "Klamath", "slug": "klamath"},
  {"name": "'Amuwu", "slug": "purisemeo"},
  {"name": "Sandawe", "slug": "sandawe"},
  {"name": "Payómkawichum (Luiseño)", "slug": "luiseo"},
  {"name": "Wagiman", "slug": "wagiman"},
  {"name": "Me-Wuk (Bay Miwok)", "slug": "bay-miwok"},
  {"name": "Mvskoke (Muscogee / Creek)", "slug": "muscogee-creek"},
  {"name": "Yupangathi", "slug": "yupangathi"},
  {"name": "Ngāti Pūkenga", "slug": "ngati-pukenga"},
  {"name": "Paipai (Akwa'ala)", "slug": "paipai-akwaala"},
  {"name": "Hia-Ced O'odham", "slug": "hia-ced-oodham"},
  {"name": "Tepehuán", "slug": "tepehun"},
  {"name": "Ngāti Mutunga", "slug": "ngati-mutunga"},
  {"name": "Ngāti Whare", "slug": "ngati-whare"},
  {
    "name": "Te Korowai o Wainuiārua (Central Whanganui)",
    "slug": "te-korowai-o-wainuiarua-central-whanganui"
  },
  {"name": "Salasaka", "slug": "salasaka"},
  {
    "name": "Mississaugas of the Credit First Nation",
    "slug": "mississaugas-of-the-credit-first-nation"
  },
  {"name": "Jarawara", "slug": "jarawara"},
  {"name": "Somi Se'k (Esto’k Gna)", "slug": "carrizo-comecrudo"},
  {"name": "Te Aitanga ā Māhaki", "slug": "te-aitanga-a-mahaki"},
  {"name": "Kisêdjê", "slug": "kisedje"},
  {"name": "Nawa", "slug": "nawa"},
  {"name": "Jaqaru", "slug": "jaqaru"},
  {"name": "Ngāti Whanaunga", "slug": "ngati-whanaunga"},
  {"name": "Dhirari", "slug": "dhirari"},
  {"name": "Gunadule (Kuna-Tule)", "slug": "guna-dule"},
  {"name": "Cession 362", "slug": "cession-362-2"},
  {"name": "Warekena", "slug": "warekena"},
  {"name": "Xetá", "slug": "xeta"},
  {"name": "Yaminawá", "slug": "yaminawa"},
  {"name": "Guanahatabey", "slug": "guanahatabey"},
  {"name": "Dokapuara (Tuyuca)", "slug": "dokapuara-tuyuca"},
  {
    "name": "Chontal de Guerrero – Tuxteco",
    "slug": "chontal-de-guerrero-tuxteco"
  },
  {"name": "Maijuna", "slug": "maijuna"},
  {"name": "Shigom", "slug": "shigom"},
  {"name": "Quillacinga", "slug": "quillacinga"},
  {"name": "Slijuala Xanuc (Chontal)", "slug": "chontal"},
  {"name": "Caddo", "slug": "caddo"},
  {"name": "Merrick", "slug": "merrick"},
  {"name": "Ngaanyatjarra", "slug": "ngaanyatjarra"},
  {"name": "komi voitõr", "slug": "komi-voitor"},
  {"name": "Tapuika", "slug": "tapuika"},
  {"name": "Erie", "slug": "erie"},
  {"name": "Acho Dene Koe", "slug": "acho-dene-koe"},
  {"name": "Djabuganjdji", "slug": "djabuganjdji"},
  {"name": "Tocobaga", "slug": "tocobaga"},
  {"name": "Ngāti Tahu / Ngāti Whaoa", "slug": "ngati-tahu-ngati-whaoa"},
  {"name": "Geawegal", "slug": "geawegal"},
  {"name": "Sanapaná", "slug": "sanapana"},
  {"name": "Awajún", "slug": "awajun"},
  {"name": "Ngāti Toa Rangatira", "slug": "ngati-toa-rangatira"},
  {"name": "Kusso", "slug": "kusso"},
  {"name": "Osage (Oklahoma)", "slug": "osage-oklahoma"},
  {"name": "Wôpanâak (Wampanoag)", "slug": "wampanoag"},
  {"name": "Turrbal", "slug": "turrbal"},
  {"name": "Abitibiwinni Aki", "slug": "abitibiwinni-aki"},
  {"name": "Kulina Pano", "slug": "kulina-pano"},
  {"name": 'Ye"pâ-masa', "slug": "yepa-masa"},
  {"name": "Lower Tohono O’odham (Lower Pima)", "slug": "pima-tohono-oodham"},
  {"name": "Kija", "slug": "kija"},
  {"name": "Tsnungwe", "slug": "tsnungwe"},
  {"name": "Nimanburu", "slug": "nimanburu"},
  {"name": "Garawa", "slug": "garawa"},
  {"name": "Sana", "slug": "sanan"},
  {"name": "Charka", "slug": "charka"},
  {"name": "Mundurukânia (Wuy jugu)", "slug": "mundurukania-wuy-jugu"},
  {"name": "Akan", "slug": "akan"},
  {"name": "Ngombur", "slug": "ngombur"},
  {"name": "Alyawarre", "slug": "alyawarre"},
  {"name": "Ãwa", "slug": "awa"},
  {"name": "Siuslaw", "slug": "siuslaw"},
  {"name": "NunatuKavut", "slug": "southern-inuit-nunatukavut"},
  {"name": "Kokatha", "slug": "kokatha"},
  {"name": "Winda Winda", "slug": "winda-winda"},
  {"name": "Ngāti Maru (Hauraki)", "slug": "ngati-maru-hauraki"},
  {"name": "Qhara Qhara", "slug": "qhara-qhara"},
  {"name": "Djabwurung", "slug": "djabwurung"},
  {"name": "Kichwa", "slug": "kichwa"},
  {"name": "Kojomk'awi (Konkow)", "slug": "konkow-maidu"},
  {"name": "Ka'apor", "slug": "kaapor"},
  {"name": "Akimel O'odham (Upper Pima)", "slug": "akimel-oodham"},
  {"name": "Unggarangi", "slug": "unggarangi"},
  {"name": "Ngāti Maru (Hauraki)", "slug": "ngati-maru-hauraki"},
  {"name": "Nimiipuu (Nez Perce)", "slug": "nimiipuu-nez-perce"},
  {"name": "Tonkawa (Oklahoma)", "slug": "tonkawa-oklahoma"},
  {
    "name": "Confederated Tribes of Grand Ronde",
    "slug": "confederated-tribes-of-grand-ronde"
  },
  {"name": "Southeastern Pomo", "slug": "southeastern-pomo"},
  {"name": "Kañari", "slug": "kanari"},
  {"name": "Ngāti Porou", "slug": "ngati-porou"},
  {"name": "A'uwe", "slug": "auwe"},
  {"name": "Ohlone", "slug": "ohlone"},
  {"name": "Chickahominy", "slug": "chickahominy"},
  {"name": "Chinantla (Tsa ju jmí’)", "slug": "chinanteco"},
  {"name": "Giya", "slug": "giya"},
  {"name": "Zacateco ", "slug": "zacateco"},
  {"name": "Nahua (Michoacan)", "slug": "nahuatl-8"},
  {"name": "Yazne", "slug": "yazne"},
  {"name": "Suquamish", "slug": "suquamish"},
  {"name": "Gagudju", "slug": "gagudju"},
  {"name": "Kunja", "slug": "kunja"},
  {"name": "Marubo", "slug": "marubo"},
  {"name": "Odawa", "slug": "odawa"},
  {"name": "Nauset", "slug": "nauset"},
  {"name": "Iwaidja", "slug": "iwaidja"},
  {"name": "Maung", "slug": "maung"},
  {"name": "Nuwuvi (Southern Paiute)", "slug": "southern-paiute"},
  {"name": "Ngāti Hei", "slug": "ngati-hei"},
  {"name": "Nyamal", "slug": "nyamal"},
  {"name": "Miluk Coos", "slug": "miluk-coos"},
  {"name": "Warriyangga", "slug": "warriyangga"},
  {"name": "Yanga", "slug": "yanga"},
  {"name": "Marringarr", "slug": "marringarr"},
  {"name": "Cayuse, Umatilla and Walla Walla", "slug": "umatilla"},
  {"name": "Copuces", "slug": "copuces"},
  {"name": "Quinault", "slug": "quinault"},
  {"name": "Pakajaqi", "slug": "pakajaqi"},
  {"name": "Southern Pomo", "slug": "southern-pomo"},
  {"name": "Ngāti Maru (Hauraki)", "slug": "ngati-maru-hauraki"},
  {"name": "Tanigua", "slug": "tanigua"},
  {"name": "Obispeño", "slug": "obispeo"},
  {"name": "Wuli-wuli", "slug": "wuli-wuli"},
  {"name": "Ngarrindjeri", "slug": "ngarrindjeri"},
  {"name": "Guató", "slug": "guato"},
  {"name": "Bardi", "slug": "bardi"},
  {"name": "Skagit", "slug": "skagit"},
  {"name": "Whakatōhea", "slug": "whakatohea"},
  {"name": "Yambina", "slug": "yambina"},
  {"name": "Ngāpuhi", "slug": "ngapuhi"},
  {"name": "Pech", "slug": "pech"},
  {"name": "Ngāti Whanaunga", "slug": "ngati-whanaunga"},
  {"name": "Tłı̨chǫ Ndè", "slug": "tlicho-agreement"},
  {"name": "Ngāti Whanaunga", "slug": "ngati-whanaunga"},
  {"name": "Chahta Yakni (Choctaw)", "slug": "chahta-choctaw"},
  {"name": "Gananggalinda", "slug": "gananggalinda"},
  {"name": "Yarluyandi", "slug": "yarluyandi"},
  {"name": "Kurâ", "slug": "kura"},
  {"name": "Cholulteca", "slug": "cholulteca"},
  {"name": "Yuru", "slug": "yuru"},
  {"name": "Wawula", "slug": "wawula"},
  {"name": "Kuyam", "slug": "kuyam"},
  {"name": "Tecuexe", "slug": "tecuexe"},
  {"name": "Wyandot (Anderdon)", "slug": "wyandot-anderdon"},
  {"name": "Kiskiack", "slug": "kiskiack"},
  {"name": "Podunks", "slug": "podunks"},
  {"name": "Madija", "slug": "madija"},
  {"name": "Aónikenk (Tehuelche)", "slug": "mapuche-tehuelche"},
  {
    "name": "Ngāti Porou ki Harataunga ki Mataora",
    "slug": "ngati-porou-ki-harataunga-ki-mataora"
  },
  {"name": "Nyangumarda", "slug": "nyangumarda"},
  {"name": "Eastern Mono/Monache", "slug": "eastern-mono-monache"},
  {"name": "Nissaquogue", "slug": "nissaquogue"},
  {"name": "Wadi Wadi", "slug": "wadi-wadi"},
  {"name": "Khanty/Kantyk", "slug": "khanty-kantyk"},
  {"name": "Sataré-Mawé", "slug": "satare-mawe"},
  {"name": "Eastern Nehântick", "slug": "eastern-nehantick"},
  {"name": "Guahibo/Hiwi", "slug": "sikuani-guajibo"},
  {"name": "Bibbulman", "slug": "bibbulman"},
  {"name": "Takla", "slug": "takla"},
  {"name": "Aché", "slug": "ache"},
  {"name": "Unangam Tanangin (Unangax̂ /Aleut)", "slug": "aleut"},
  {"name": "Ngāti Korokī Kahukura", "slug": "ngati-koroki-kahukura"},
  {"name": "Ofaié", "slug": "ofaie"},
  {"name": "Ts’uubaa-asatx", "slug": "tsuubaa-asatx"},
  {"name": "Wappo", "slug": "wappo"},
  {"name": "Ngātiwai", "slug": "ngatiwai"},
  {"name": "Biri", "slug": "biri"},
  {"name": "Sobaipuri", "slug": "sobaipuri"},
  {"name": "Kamilaroi", "slug": "kamilaroi"},
  {"name": "Mojeño", "slug": "mojeno"},
  {"name": "Mattaponi", "slug": "mattaponi"},
  {"name": "Piscataway", "slug": "piscataway"},
  {"name": "Karjalaiset (Karelian)", "slug": "karjalaiset-karelian"},
  {"name": "Dehcho Dene", "slug": "dehcho-dene"},
  {"name": "Monqui", "slug": "monqui"},
  {"name": "Gamberre", "slug": "gamberre"},
  {"name": "Chankas", "slug": "chankas"},
  {"name": "Nasa", "slug": "nasa"},
  {"name": "Cuitlatec", "slug": "cuitlatec"},
  {"name": "Shmuwich (Barbareño)", "slug": "barbareno"},
  {"name": "Asheninka", "slug": "asheninka"},
  {"name": "Wanano/Kotiria", "slug": "wanano-kotiria"},
  {"name": "Ngatatjara", "slug": "ngatatjara"},
  {"name": "Miccosukee", "slug": "miccosukee"},
  {"name": "Kumeyaay", "slug": "kumeyaay"},
  {"name": "Ngāti Kahu", "slug": "ngati-kahu"},
  {"name": "Willapa", "slug": "willapa"},
  {"name": "Gungabula", "slug": "gungabula"},
  {
    "name": "nuučaan̓uuɫɁatḥ nism̓a (Nuu-chah-nulth)",
    "slug": "nuu-chah-nulth-tribal-council"
  },
  {"name": "Kaantju", "slug": "kaantju"},
  {"name": "Acjachemen (Juaneño)", "slug": "acjachemen-juaneno"},
  {"name": "Clatskanie", "slug": "clatskanie"},
  {"name": "Squaxin", "slug": "squaxin"},
  {"name": "Warluwarra", "slug": "warluwarra"},
  {"name": "Yoncalla", "slug": "yoncalla"},
  {"name": "Moratok", "slug": "moratok"},
  {"name": "Ngāi Tai ki Tāmaki", "slug": "ngai-tai-ki-tamaki"},
  {"name": "Kisii", "slug": "kisii"},
  {"name": "Wiyot", "slug": "wiyot"},
  {"name": "Yankton", "slug": "yankton-2"},
  {"name": "Lenca", "slug": "lenca"},
  {"name": "Mayi-Yapi", "slug": "mayi-yapi"},
  {"name": "Sahtú Got’ine", "slug": "sahtu-gotine"},
  {"name": "Ngamini", "slug": "ngamini"},
  {"name": "Giraiwurung", "slug": "giraiwurung"},
  {"name": "Biripi", "slug": "biripi"},
  {"name": "Umukomasã/Desana", "slug": "umukomasa-desana"},
  {"name": "Ngāti Manuhiri", "slug": "ngati-manuhiri"},
  {"name": "Chehalis", "slug": "chehalis"},
  {"name": "Appamattuck", "slug": "appamattuck"},
  {"name": "U'wa", "slug": "uwa"},
  {"name": "Karenggapa", "slug": "karenggapa"},
  {"name": "Swinomish", "slug": "swinomish"},
  {"name": "BOḰEĆEN (Pauquachin)", "slug": "boḱecen-pauquachin"},
  {"name": "Onawmanient", "slug": "onawmanient"},
  {"name": "Bigambul", "slug": "bigambul"},
  {"name": "Clackamas", "slug": "clackamas"},
  {"name": "Cuica", "slug": "cuica"},
  {"name": "Tomabela", "slug": "tomabela"},
  {"name": "Parkatejê", "slug": "parkateje"},
  {"name": "Menominee", "slug": "menominee"},
  {"name": "Chalon", "slug": "chalon"},
  {"name": "Neusiok", "slug": "neusiok-2"},
  {"name": "Agwarmin", "slug": "agwarmin"},
  {"name": "Vanyumé", "slug": "vanyume"},
  {"name": "Matsigenka", "slug": "matsigenka"},
  {"name": "Tanacross", "slug": "tanacross"},
  {"name": "Warwa", "slug": "warwa"},
  {"name": "Cherokee (Oklahoma)", "slug": "cherokee-oklahoma"},
  {"name": "Lucayo", "slug": "lucayo"},
  {"name": "Salmon River", "slug": "salmon-river"},
  {"name": "Cahto", "slug": "cahto"},
  {"name": "Kayambi", "slug": "kayambi"},
  {"name": "Croatan", "slug": "croatan"},
  {"name": "Ngāti Apa ki te Rā Tō", "slug": "ngati-apa-ki-te-ra-to"},
  {"name": "Te Patukirikiri", "slug": "te-patukirikiri"},
  {"name": "Enawenê-nawê", "slug": "enawene-nawe"},
  {"name": "Maańśi", "slug": "maansi"},
  {"name": "Ngāti Rangiteaorere", "slug": "ngati-rangiteaorere"},
  {"name": "Quw'utsun", "slug": "quwutsun"},
  {"name": "Rikbaktsá", "slug": "rikbaktsa"},
  {"name": "Pueblos", "slug": "pueblos"},
  {"name": "Nambikwara", "slug": "nambikwara"},
  {"name": "Gayardilt", "slug": "gayardilt"},
  {"name": "Yangga", "slug": "yangga"},
  {"name": "Ngāi Tahu", "slug": "ngai-tahu"},
  {"name": "Wasco and Wishram", "slug": "wasco-and-wishram"},
  {"name": "Quandamooka", "slug": "quandamooka"},
  {"name": "Kaimbé", "slug": "kaimbe"},
  {"name": "Te Patukirikiri", "slug": "te-patukirikiri"},
  {"name": "Pamlico (Pomouik)", "slug": "pamlico-pomouik"},
  {"name": "Tāłtān Konelīne (Tahltan)", "slug": "tahltan"},
  {"name": "Wemba Wemba", "slug": "wemba-wemba"},
  {"name": "Canela Apanyekrá", "slug": "canela-apanyekra"},
  {"name": "Kitasoo/Xai'xais", "slug": "kitasoo"},
  {"name": "Nükak Makü", "slug": "nukak-maku"},
  {"name": "Tetlit Gwich’in", "slug": "tetlit-gwich-in"},
  {"name": "Alawa", "slug": "alawa"},
  {"name": "Chelamela", "slug": "long-tom"},
  {"name": "Mannansett", "slug": "mannansett"},
  {"name": "Te Patukirikiri", "slug": "te-patukirikiri"},
  {"name": "Anambé", "slug": "anambe"},
  {"name": "Halíti", "slug": "haliti"},
  {"name": "Xinca", "slug": "xinca"},
  {"name": "Ngāi Tai ki Tāmaki", "slug": "ngai-tai-ki-tamaki"},
  {"name": "Tulalip", "slug": "tulalip"},
  {"name": "Waípinõmakã (Bará)", "slug": "waipinomaka-bara"},
  {"name": "Matetamãe/Cinta Larga", "slug": "matetamae-cinta-larga"},
  {"name": "Cow Creek Umpqua", "slug": "cow-creek-umpqua"},
  {"name": "Arara of Volta Grande", "slug": "arara-of-volta-grande"},
  {"name": "Tigua", "slug": "tigua"},
  {"name": "Wateree", "slug": "wateree"},
  {"name": "Yuin", "slug": "yuin"},
  {"name": "Waveroo", "slug": "waveroo"},
  {"name": "Te Patukirikiri", "slug": "te-patukirikiri"},
  {"name": "Bayali", "slug": "bayali"},
  {"name": "Yangman", "slug": "yangman"},
  {"name": "Tillamook", "slug": "tillamook-2"},
  {"name": "Ngāi Tai ki Tāmaki", "slug": "ngai-tai-ki-tamaki"},
  {"name": "Kitanemuk", "slug": "kitanemuk"},
  {"name": "Gunditjmara", "slug": "gunditjmara"},
  {"name": "Taos Pueblo", "slug": "taos-pueblo"},
  {"name": "Nunavik", "slug": "nunavik"},
  {"name": "Sac and Fox (Oklahoma)", "slug": "sac-fox-oklahoma"},
  {"name": "Sahtu Dene and Metis", "slug": "sahtu-dene-and-metis"},
  {"name": "Wirangu", "slug": "wirangu"},
  {"name": "Sanavirones", "slug": "sanavirones"},
  {"name": "Budjari", "slug": "budjari"},
  {"name": "Apiaká", "slug": "apiaka"},
  {"name": "Palouse", "slug": "palouse"},
  {"name": "Tenetehara (Tembé)", "slug": "tenetehara-tembe"},
  {"name": "Kalapalo", "slug": "kalapalo"},
  {"name": "Ngawun", "slug": "ngawun"},
  {"name": "Tanana", "slug": "tanana"},
  {"name": "ɬaʔamɩn gɩǰɛ (Tla'amin/Sliammon)", "slug": "sliammon"},
  {
    "name": "Confederated Tribes of Siletz Indians",
    "slug": "confederated-tribes-of-siletz-indians"
  },
  {"name": "Parikwene", "slug": "parikwene"},
  {"name": "Pit River", "slug": "pit-river"},
  {"name": "Arapaho", "slug": "arapaho"},
  {"name": "Ngāti Rehua", "slug": "ngati-rehua"},
  {"name": "Barunggam", "slug": "barunggam"},
  {"name": "Baradha", "slug": "baradha"},
  {"name": "Hupd'äh", "slug": "hupdah"},
  {"name": "Wari’", "slug": "wari"},
  {"name": "Waitaha", "slug": "waitaha"},
  {"name": "Skwxwú7mesh-ulh Temíx̱w (Squamish)", "slug": "skwxw7mesh-xwumixw"},
  {
    "name": "Taranaki Whānui ki te Upoko o te Ika",
    "slug": "taranaki-whanui-ki-te-upoko-o-te-ika"
  },
  {"name": "Tjungundji", "slug": "tjungundji"},
  {"name": "S’ólh Téméxw (Stó:lō)", "slug": "sto-lo-treaty-association"},
  {"name": "Timotes", "slug": "timotes"},
  {"name": "Lower Chinook", "slug": "lower-chinook-2"},
  {"name": "Gitxaała", "slug": "gitxaala"},
  {"name": "Ngāti Tamaoho", "slug": "ngati-tamaoho"},
  {"name": "Yaruro/Pumé", "slug": "pume"},
  {"name": "Movima", "slug": "movima"},
  {"name": "Inuvialuit", "slug": "inuvialut"},
  {"name": "Musgamagw Dzawada'enuxw", "slug": "musgamagw-dzawadaenuxw"},
  {"name": "Muwekma", "slug": "muwekma"},
  {"name": "Uchucklesaht", "slug": "uchucklesaht"},
  {"name": "Dënéndeh", "slug": "denendeh"},
  {"name": "Dieri", "slug": "dieri"},
  {"name": "Kwini", "slug": "kwini"},
  {"name": "Waranka", "slug": "waranka"},
  {"name": "Waikato", "slug": "waikato"},
  {"name": "Mutumui", "slug": "mutumui"},
  {"name": "Walangama", "slug": "walangama"},
  {"name": "Apyãwa", "slug": "apyawa"},
  {"name": "Werowocomoco", "slug": "werowocomoco"},
  {"name": "Kisapincha", "slug": "kisapincha"},
  {"name": "Mazahua", "slug": "mazahua"},
  {"name": "Chochenyo", "slug": "chochenyo"},
  {"name": "Jardwadjali", "slug": "jardwadjali"},
  {"name": "Homalco", "slug": "homalco"},
  {"name": "Kamejeya (Yukuna)", "slug": "kamejeya-yukuna"},
  {"name": "Setauket", "slug": "setauket"},
  {"name": "Nom Sus Wintu", "slug": "nom-sus-wintu"},
  {"name": "Salish Kootenai (Flathead)", "slug": "salish-flathead"},
  {"name": "Wik", "slug": "wik"},
  {"name": "Sicangu", "slug": "sicangu"},
  {
    "name": "Mount Tabor Indian Community",
    "slug": "mount-tabor-indian-community"
  },
  {"name": "Guugu-Yimidhirr", "slug": "guugu-yimidhirr"},
  {"name": "Calicuas", "slug": "calicuas"},
  {"name": "Patwin", "slug": "patwin"},
  {"name": "Wahkiakum", "slug": "wahkiakum"},
  {"name": "Tenino", "slug": "tenino"},
  {"name": "Tontotuna (Totoró)", "slug": "tontotuna-totoro"},
  {"name": "Michumash", "slug": "island-chumash"},
  {"name": "Coree", "slug": "coree"},
  {"name": "K’áálǫ Got’ine", "slug": "kaalǫ-gotine"},
  {"name": "Mebêngôkre (Kayapó)", "slug": "mebengokre-kayapo"},
  {"name": "Beaver", "slug": "beaver"},
  {"name": "Ngātiwai", "slug": "ngatiwai"},
  {"name": "Molalla", "slug": "molalla"},
  {
    "name": "Wichita-Caddo-Delaware (Oklahoma)",
    "slug": "wichita-caddo-delaware-oklahoma"
  },
  {"name": "Sumas", "slug": "sumas"},
  {"name": "Djeoromitxí", "slug": "djeoromitxi"},
  {"name": "Maká", "slug": "maka"},
  {"name": "Lickanantay", "slug": "lickanantay"},
  {"name": "Kizh", "slug": "kizh"},
  {"name": "Muaūpoko", "slug": "muaupoko"},
  {"name": "Sappony", "slug": "saponi"},
  {"name": "Tapieté/Guaraní-Ñandeva", "slug": "tapiete-guarani-nandeva"},
  {"name": "Kashaya", "slug": "kashaya"},
  {"name": "Bohanes", "slug": "bohanes"},
  {"name": "Peoria (Oklahoma)", "slug": "peoria-oklahoma"},
  {"name": "Ngarabal", "slug": "ngarabal"},
  {"name": "Wichita", "slug": "wichita"},
  {"name": "Anggamudi", "slug": "anggamudi"},
  {"name": "Myaamia", "slug": "miami"},
  {"name": "Aikanã", "slug": "aikana"},
  {"name": "Wari", "slug": "wari-2"},
  {"name": "Catawba", "slug": "catawba"},
  {"name": "Poqomam", "slug": "poqomam"},
  {"name": "Luthigh", "slug": "luthigh"},
  {"name": "Pitta-Pitta", "slug": "pitta-pitta"},
  {"name": "Montaukett", "slug": "montauk"},
  {"name": "Dau Pom Wintu", "slug": "dau-pom-wintu"},
  {"name": "No'iria", "slug": "noiria"},
  {"name": "Djargurdwurung", "slug": "djargurdwurung"},
  {"name": "Kala Lagaw Ya", "slug": "kala-lagaw-ya"},
  {"name": "Karijona", "slug": "karijona"},
  {"name": "Eyak", "slug": "eyak"},
  {"name": "Huaylas", "slug": "huaylas"},
  {"name": "Onʌyote'a•ka (Oneida)", "slug": "oneida"},
  {"name": "Pentucket", "slug": "pentucket"},
  {"name": "Narangga", "slug": "narangga"},
  {"name": "Pokanoket", "slug": "pokanoket"},
  {"name": "Timucua", "slug": "timucua"},
  {"name": "Larrakia", "slug": "larrakia"},
  {"name": "Makah", "slug": "makah"},
  {"name": "Amangu", "slug": "amangu"},
  {"name": "Yeopim", "slug": "yeopim"},
  {"name": "Canarsie", "slug": "canarsie"},
  {"name": "Selk'nam", "slug": "selknam"},
  {"name": "Cuicuilco", "slug": "cuicuilco"},
  {"name": "Á,LEṈENEȻ ȽTE (W̱SÁNEĆ)", "slug": "w-sne"},
  {"name": "Deni", "slug": "deni"},
  {"name": "Gulidjan", "slug": "gulidjan"},
  {"name": "Cheraw", "slug": "cheraw"},
  {"name": "Kichwa Santarrosino", "slug": "kichwa-santarrosino"},
  {"name": "Tsase/Piapoco", "slug": "tsase-piapoco"},
  {"name": "Ngāi Tai ki Tāmaki", "slug": "ngai-tai-ki-tamaki"},
  {"name": "Baure", "slug": "baure"},
  {"name": "Paugussett", "slug": "paugussett"},
  {"name": "Yanyuwa", "slug": "yanuwa"},
  {"name": "Takalak", "slug": "takalak"},
  {"name": "Ngāti Tara Tokanui", "slug": "ngati-tara-tokanui"},
  {"name": "Haida Gwaii", "slug": "haida"},
  {"name": "Patamona/Ingarikó", "slug": "patamona-ingariko"},
  {"name": "Barkindji", "slug": "barkindji"},
  {"name": "Cahuilla", "slug": "cahuilla"},
  {"name": "Chickasaw (Oklahoma)", "slug": "chickasaw-oklahoma"},
  {"name": "Thalanyji", "slug": "thalanyji"},
  {"name": "Ngāti Whanaunga", "slug": "ngati-whanaunga"},
  {"name": "Kitu Kara", "slug": "kitu-kara"},
  {"name": "Achí", "slug": "achi"},
  {"name": "Ngadjuri", "slug": "ngadjuri"},
  {"name": "Goshute", "slug": "goshute"},
  {"name": "Gungurugoni", "slug": "gungurugoni"},
  {"name": "Amboca", "slug": "amboca"},
  {"name": "Ngaliwuru", "slug": "ngaliwuru"},
  {"name": "Moriori", "slug": "moriori-2"},
  {"name": "Ngātiwai", "slug": "ngatiwai"},
  {"name": "Qayqayt", "slug": "qayqayt"},
  {"name": "Massacoes", "slug": "massacoes"},
  {"name": "Cheyenne", "slug": "cheyenne"},
  {"name": "Houma", "slug": "houma-2"},
  {"name": "Pitjantjatjara", "slug": "pitjantjatjara"},
  {"name": "Woolna", "slug": "woolna"},
  {"name": "Ngatjumay", "slug": "ngatjumay"},
  {"name": "Kaiabi", "slug": "kaiabi"},
  {"name": "Big Stone Cree", "slug": "big-stone-cree"},
  {"name": "Gwich'in Nành", "slug": "gwichin"},
  {"name": "Vacacocha", "slug": "vacacocha"},
  {"name": "Murrinh-patha", "slug": "murrinh-patha"},
  {"name": "Seminole (Oklahoma)", "slug": "seminole-oklahoma"},
  {"name": "Lamalama", "slug": "lamalama"},
  {"name": "Inkeriläinen", "slug": "inkerilainen"},
  {"name": "Winnimem Wintu", "slug": "winnimem-wintu"},
  {"name": "Kluane", "slug": "kluane"},
  {"name": "Yandruwandha", "slug": "yandruwandha"},
  {"name": "Rembarnga", "slug": "rembarnga"},
  {"name": "Tanimuka", "slug": "tanimuka"},
  {"name": "Taku River Tlingit", "slug": "taku-river-tlingit"},
  {"name": "Pijao", "slug": "pijao"},
  {
    "name": "Siekopa’aiInte/Aido-Pãi (Secoya)",
    "slug": "siekopaaiinte-aido-pai-secoya"
  },
  {"name": "Kitselas", "slug": "kitselas"},
  {"name": "Manoki", "slug": "manoki"},
  {"name": "Mokaná", "slug": "mokana"},
  {"name": "Yugambeh", "slug": "yugambeh"},
  {"name": "Ngāti Paoa", "slug": "ngati-paoa"},
  {"name": "Kuuvuan KaNianiq", "slug": "kuuvuan-kanianiq"},
  {"name": "Ayoreo", "slug": "ayoreo"},
  {"name": "Wolastoqiyik Wahsipekuk (Maliseet)", "slug": "maliseet-2"},
  {"name": "Kankuamo", "slug": "kankuamo"},
  {"name": "Kundjey’mi", "slug": "kundjeymi"},
  {"name": "Makurap", "slug": "makurap"},
  {"name": "Paltas", "slug": "paltas"},
  {"name": "Enlhet", "slug": "enlhet"},
  {"name": "Dena'ina Ełnena", "slug": "tanaina"},
  {"name": "Añuu", "slug": "anuu"},
  {"name": "Wardandi", "slug": "wardandi"},
  {"name": "Unkechaug", "slug": "unkechaug"},
  {"name": "Araona", "slug": "araona"},
  {"name": "Pescado", "slug": "pescado"},
  {"name": "Nʉmʉnʉʉ (Comanche)", "slug": "nmn-comanche"},
  {"name": "Umida", "slug": "umida"},
  {"name": "Massapequas", "slug": "massapequas"},
  {"name": "Malyangaba", "slug": "malyangaba"},
  {"name": "Mescalero Apache", "slug": "mescalero-apache"},
  {"name": "Marinahua", "slug": "marinahua"},
  {"name": "Dakeł Keyoh (ᑕᗸᒡ ᗲᘏᑋ)", "slug": "dakelh"},
  {"name": "Resígaro", "slug": "resigaro"},
  {"name": "Kurnai", "slug": "kurnai"},
  {"name": "Hixkaryana", "slug": "hixkaryana"},
  {"name": "Ngāti Maru (Hauraki)", "slug": "ngati-maru-hauraki"},
  {"name": "Mississauga", "slug": "mississauga"},
  {"name": "Ch'orti'", "slug": "chorti"},
  {"name": "Kichwa del Río Napo", "slug": "kichwa-del-rio-napo"},
  {"name": "Pisamira", "slug": "pisamira"},
  {"name": "Xixime", "slug": "xixime-2"},
  {"name": "Waíkhana", "slug": "waikhana"},
  {"name": "Hñähñu (Otomí)", "slug": "hnahnu-otomi"},
  {"name": "Amarak", "slug": "amarak"},
  {"name": "KiKiallus", "slug": "kikiallus"},
  {"name": "Pâri (Pawnee)", "slug": "pawnee"},
  {"name": "Yaros", "slug": "yaros"},
  {"name": "Söl'kup", "slug": "solkup"},
  {"name": "Watjarri", "slug": "watjarri"},
  {"name": "Dharug", "slug": "dharug"},
  {"name": "Qwû'lh-hwai-pûm (Klickitat)", "slug": "qwulh-hwai-pum-klickitat"},
  {"name": "Wappinger", "slug": "wappinger-2"},
  {"name": "Raukawa", "slug": "raukawa"},
  {"name": "Congaree", "slug": "congaree"},
  {"name": "Trio/Wü tarëno", "slug": "trio"},
  {"name": "Kokowarra", "slug": "kokowarra"},
  {"name": "Modoc (Oklahoma)", "slug": "modoc-oklahoma"},
  {"name": "Nor Rel Muk Wintu", "slug": "nor-rel-muk-wintu"},
  {"name": "Ngāti Rongomai", "slug": "ngati-rongomai"},
  {"name": "Wangunks", "slug": "wangunks"},
  {"name": "N’eney N’enet’s’ (Nenets)", "slug": "neney-nenets-nenets"},
  {"name": "Yukpa", "slug": "yukpa"},
  {"name": "Jupaú (Kawahib)", "slug": "jupau-kawahib"},
  {"name": "Ulwas", "slug": "ulwas"},
  {"name": "Trumai", "slug": "trumai"},
  {"name": "Ngāti Hineuru", "slug": "ngati-hineuru"},
  {"name": "Ngāti Rārua", "slug": "ngati-rarua"},
  {"name": "Rapa Nui", "slug": "rapa-nui"},
  {"name": "Nomatsigenga", "slug": "nomatsigenga"},
  {"name": "Te Kawerau a Maki", "slug": "te-kawerau-a-maki"},
  {"name": "Ngāti Paoa", "slug": "ngati-paoa"},
  {"name": "Pawnee (Oklahoma)", "slug": "pawnee-oklahoma"},
  {"name": "Yamhill", "slug": "yamhill"},
  {"name": "Moneton", "slug": "moneton"},
  {"name": "O-ga-xpa Ma-zhoⁿ (O-ga-xpa)", "slug": "quapaw"},
  {"name": "Palyku", "slug": "palyku"},
  {"name": "Tommeginne", "slug": "tommeginne"},
  {"name": "Bidai", "slug": "bidai"},
  {"name": "Ngarti", "slug": "ngarti"},
  {"name": "Huasteco/Teenek", "slug": "huastecoteenek"},
  {"name": "Northern Pomo", "slug": "northern-pomo"},
  {"name": "Lassik", "slug": "lassik"},
  {"name": "Ngāti Whanaunga", "slug": "ngati-whanaunga"},
  {"name": "Mountain Maidu", "slug": "mountain-maidu"},
  {"name": "Chukchansi", "slug": "chukchansi"},
  {"name": "Mochó", "slug": "moch"},
  {"name": "Thul Garrie Waja (Bindal)", "slug": "bindal"},
  {"name": "Waazija (Ho-Chunk / Winnebago)", "slug": "ho-chunk-winnebago"},
  {"name": "Wathaurong", "slug": "wathaurong"},
  {"name": "Eastern Shawnee (Oklahoma)", "slug": "eastern-shawnee-oklahoma"},
  {"name": "Kaska Dena Kayeh", "slug": "kaska-dena"},
  {"name": "Pirlatapa", "slug": "pirlatapa"},
  {"name": "Kurtjar", "slug": "kurtjar"},
  {"name": "Baré", "slug": "bare"},
  {"name": "Vuntut Gwitchin", "slug": "vuntut-gwitchin"},
  {"name": "Wiilman", "slug": "wiilman"},
  {"name": "Omàmìwininìwag (Algonquin)", "slug": "algonquin"},
  {"name": "Pankará", "slug": "pankara"},
  {"name": "Newe (Western Shoshone)", "slug": "newe-western-shoshone"},
  {"name": "Pocomoke", "slug": "pocomoke"},
  {"name": "Cochimí", "slug": "cochim"},
  {"name": "Adena", "slug": "adena"},
  {"name": "Yihamwo (Yagua)", "slug": "yihamwo-yagua"},
  {"name": "Ngāti Kuia", "slug": "ngati-kuia"},
  {"name": "Rangitāne", "slug": "rangitane"},
  {"name": "Kawahib (Parintintin)", "slug": "kagwahiva-parintintin"},
  {"name": "Deg Xit'an Ngan' (Deg Xit'an)", "slug": "deg-hitan"},
  {"name": "Dangbon", "slug": "dangbon"},
  {"name": "Pinjarup", "slug": "pinjarup"},
  {"name": "Kukatj", "slug": "kukatj"},
  {"name": "Chowanoke", "slug": "chowanoke"},
  {"name": "Winefelly", "slug": "winefelly"},
  {"name": "Tŝilhqot’in Nen", "slug": "tsilqotin"},
  {"name": "Kwazá", "slug": "kwaza"},
  {"name": "Yine", "slug": "yine"},
  {"name": "Ecuana", "slug": "ecuana"},
  {"name": "Ngāpuhi", "slug": "ngapuhi"},
  {"name": "Wuthathi", "slug": "wuthathi"},
  {"name": "Misak", "slug": "misak"},
  {"name": "Ngāti Hauiti", "slug": "ngati-hauiti"},
  {"name": "Yurutí", "slug": "yuruti"},
  {"name": "Tagish", "slug": "tagish"},
  {"name": "Warao", "slug": "warao"},
  {"name": "Pascua Yaqui", "slug": "pascua-yaqui"},
  {"name": "Banawá", "slug": "banawa"},
  {"name": "Paspahegh", "slug": "paspahegh"},
  {"name": "Akaitcho", "slug": "akaitcho"},
  {"name": "Te Aupōuri", "slug": "te-aupouri"},
  {"name": "Hualapai", "slug": "hualapai"},
  {"name": "Mnicoujou", "slug": "mnicoujou"},
  {"name": "Te Uri o Hau", "slug": "te-uri-o-hau"},
  {"name": "Denendeh (Dënësųłinë́ Nëné)", "slug": "dene-chipewyan"},
  {"name": "Yolngu", "slug": "yolngu"},
  {"name": "Wicocomico", "slug": "wicocomico"},
  {"name": "W̱SĺḴEM (Tseycum)", "slug": "w̱slḵem-tseycum"},
  {"name": "Nuenonne", "slug": "nuenonne"},
  {"name": "Te’mexw Treaty Association", "slug": "te-mexw-treaty-association"},
  {"name": "Leco", "slug": "leco"},
  {"name": "Kadiwéu", "slug": "kadiweu"},
  {"name": "Skykomish", "slug": "skykomish"},
  {"name": "Kashtik ", "slug": "kashtik"},
  {"name": "Great Lakes Twa", "slug": "great-lakes-twa"},
  {"name": "Moose Cree", "slug": "moose-cree"},
  {"name": "Ngāti Ruanui", "slug": "ngati-ruanui"},
  {"name": "Ngāti Rangiwewehi", "slug": "ngati-rangiwewehi"},
  {"name": "Kwantlen", "slug": "kwantlen"},
  {"name": "Chimariko (territory)", "slug": "chimariko"},
  {"name": "Sakurabiat", "slug": "sakurabiat"},
  {"name": "Matagalpa/Cacaopera", "slug": "matagalpa-cacaopera"},
  {"name": "Stz'uminus", "slug": "stzuminus"},
  {
    "name": "Seminole Tribe of Florida (Tampa Reservation)",
    "slug": "seminole-tribe-of-florida-tampa-reservation"
  },
  {"name": "Bora", "slug": "bora"},
  {"name": "Maya Yucateco", "slug": "maya-yucateco"},
  {"name": "Lokono (Arawak)", "slug": "lokono-arawak"},
  {"name": "Wardaman", "slug": "wardaman"},
  {"name": "Umurecoómajá (Tatuyo)", "slug": "umurecoomaja-tatuyo"},
  {"name": "Sekakawon", "slug": "sekakawon"},
  {"name": "Ngāti Kuri", "slug": "ngati-kuri"},
  {"name": "Ngāti Maru (Taranaki)", "slug": "ngati-maru-taranaki"},
  {"name": "Wendake-Nionwentsïo", "slug": "huron-wendat"},
  {"name": "Weyanock", "slug": "weyanock"},
  {"name": "Dagomba", "slug": "dagomba"},
  {"name": "Awaswas", "slug": "awaswas"},
  {"name": "Ngāti Tamaterā", "slug": "ngati-tamatera"},
  {"name": "Karajá do Norte", "slug": "karaja-do-norte"},
  {"name": "Abenaki / Abénaquis", "slug": "abenaki-abnaquis"},
  {
    "name": "WiYaPeMiAk (Weapemeoc-Yeopim)",
    "slug": "wiyapemiak-weapemeoc-yeopim"
  },
  {"name": "Zo’é", "slug": "zoe"},
  {"name": "Kalapuya", "slug": "kalapuya"},
  {"name": "Nanti", "slug": "nanti"},
  {"name": "Bribri", "slug": "bribri"},
  {"name": "Konomihu", "slug": "konomihu"},
  {"name": "Ngāti Tara Tokanui", "slug": "ngati-tara-tokanui"},
  {"name": "Warray", "slug": "warray"},
  {"name": "Jurruru", "slug": "malpa"},
  {"name": "Peerapper", "slug": "peerapper"},
  {"name": "Chimú", "slug": "chimu"},
  {"name": "Núu-agha-tʉvʉ-pʉ̱ (Ute)", "slug": "ute"},
  {"name": "Hohokam", "slug": "hohokam"},
  {"name": "Pequawket", "slug": "pequawket"},
  {"name": "Tuscarora", "slug": "tuscarora-3"},
  {"name": "Ngāti Toa Rangatira", "slug": "ngati-toa-rangatira"},
  {"name": "Kukatja", "slug": "kukatja"},
  {"name": "Kalaw Kawaw Ya", "slug": "kalaw-kawaw-ya"},
  {"name": "Taino", "slug": "taino"},
  {"name": "Iningai", "slug": "iningai"},
  {"name": "Lheidli T'enneh", "slug": "lheidli-tenneh"},
  {"name": "Huetar", "slug": "huetar"},
  {"name": "Pocumtuc", "slug": "pocumtuc"},
  {
    "name": "WiYaPeMiAk (Weapemeoc-Yeopim)",
    "slug": "wiyapemiak-weapemeoc-yeopim"
  },
  {"name": "Wiljali", "slug": "wiljali"},
  {"name": "Wangkangurru", "slug": "wangkangurru"},
  {"name": "Kakinte", "slug": "kakinte"},
  {"name": "Matlatzinco/matlatzinteca", "slug": "matlatzincomatlatzinteca"},
  {"name": "Tuxá", "slug": "tuxa"},
  {"name": "Rankülche", "slug": "rankulche"},
  {"name": "Tolupan", "slug": "tolupan"},
  {"name": "Te Wairoa iwi and hapu", "slug": "te-wairoa-iwi-and-hapu"},
  {"name": "Guarayo", "slug": "guarayo"},
  {"name": "Occaneechi", "slug": "occaneechi"},
  {"name": "Lekwungen/Songhees", "slug": "lekwungen-songhees"},
  {"name": "Suruwaha", "slug": "suruwaha"},
  {"name": "Huarpe", "slug": "huarpe"},
  {
    "name":
        "Nahua ( Morelos, Puebla, Tlaxcala, Veracruz, Hidalgo, San Luis Potosi)",
    "slug": "nahuatl-7"
  },
  {"name": "Wanapum", "slug": "wanapum"},
  {"name": "Latje Latje", "slug": "latje-latje"},
  {"name": "Yana", "slug": "yana"},
  {
    "name": "Seminole Tribe of Florida (Hollywood Reservation)",
    "slug": "seminole-tribe-of-florida-hollywood-reservation"
  },
  {"name": "Mingin", "slug": "mingin"},
  {"name": "Me-Wuk (Central Sierra Miwok)", "slug": "central-sierra-miwok"},
  {"name": "Central Pomo", "slug": "central-pomo"},
  {"name": "Wallmapu (Mapuche)", "slug": "mapuche"},
  {"name": "Ngāi Tai ki Tāmaki", "slug": "ngai-tai-ki-tamaki"},
  {"name": "Älsé (Alsea)", "slug": "alsea"},
  {"name": "Bidwell", "slug": "bidwell"},
  {"name": "Yagalingu", "slug": "yagalingu"},
  {"name": "Purduna", "slug": "purduna"},
  {"name": "Tyerrernotepanner", "slug": "tyerrernotepanner"},
  {"name": "Očhéthi Šakówiŋ", "slug": "oceti-sakowin-sioux"},
  {"name": "Muniche", "slug": "muniche"},
  {"name": "Gundungurra", "slug": "gundungurra"},
  {"name": "Koko-bera", "slug": "koko-bera"},
  {"name": "NWT Métis Nation", "slug": "nwt-metis-nation"},
  {"name": "Vepslaine/Vepsalne (Veps)", "slug": "vepslaine-vepsalne-veps"},
  {"name": "Ngāti Maru (Hauraki)", "slug": "ngati-maru-hauraki"},
  {"name": "Ngāti Rāhiri Tumutumu", "slug": "ngati-rahiri-tumutumu"},
  {"name": "Rangitāne o Wairau", "slug": "rangitane-o-wairau"},
  {"name": "Sturgeon Lake Cree", "slug": "sturgeon-lake-cree"},
  {"name": "Ngāti Kea / Ngāti Tuarā", "slug": "ngati-kea-ngati-tuara"},
  {
    "name": "Aseniwuche Winewak (Rocky Mountain)",
    "slug": "aseniwuche-winewak-rocky-mountain"
  },
  {"name": "Whilkut", "slug": "whilkut"},
  {"name": "Pintupi", "slug": "pintupi"},
  {"name": "Winyah", "slug": "winyah"},
  {"name": "Ngāti Tamaterā", "slug": "ngati-tamatera"},
  {"name": "Yurí", "slug": "yuri"},
  {"name": "Tawahka", "slug": "tawahka"},
  {"name": "Keyauwee", "slug": "keyauwee"},
  {
    "name": "Ngāti Mutunga o Wharekauri (Chatham Islands)",
    "slug": "ngati-mutunga-o-wharekauri-chatham-islands"
  },
  {"name": "Emberá Dobidá", "slug": "embera-dobida"},
  {"name": "Ngargad", "slug": "ngargad"},
  {"name": "Envuga (Kawahib)", "slug": "envuga-kawahib"},
  {"name": "Ahé (Kawahib)", "slug": "ahe-kawahib"},
  {"name": "Chiso", "slug": "chiso"},
  {"name": "Ngāitai (Bay Of Plenty)", "slug": "ngaitai-bay-of-plenty"},
  {"name": "Te Patukirikiri", "slug": "te-patukirikiri"},
  {"name": "Djirbalngan", "slug": "djirbalngan"},
  {"name": "Tharawal", "slug": "tharawal"},
  {"name": "Kubéwa/Cubeo", "slug": "kubewa-cubeo"},
  {"name": "Ngāi Tai ki Tāmaki", "slug": "ngai-tai-ki-tamaki"},
  {"name": "Gurindji", "slug": "gurindji"},
  {"name": "Awytyza", "slug": "awytyza"},
  {"name": "Miwa", "slug": "miwa"},
  {"name": "Chichas", "slug": "chichas"},
  {"name": "Guwinmal", "slug": "guwinmal"},
  {"name": "Ngāti Kahu ki Whangaroa", "slug": "ngati-kahu-ki-whangaroa"},
  {"name": "Nuxwsa'7aq (Nooksack)", "slug": "nuxwsa7aq-nooksack"},
  {"name": "Itazipco", "slug": "itazipco"},
  {"name": "Yanam (Ninam)", "slug": "yanam-ninam"},
  {"name": "Kuwema", "slug": "kuwema"},
  {"name": "Onundagaonoga (Onondaga)", "slug": "onondaga"},
  {"name": "Marrithiyel", "slug": "marrithiyel"},
  {"name": "Te Atiawa ki Whakarongotai", "slug": "te-atiawa-ki-whakarongotai"},
  {"name": "Ngāti Whanaunga", "slug": "ngati-whanaunga"},
  {"name": "Ngāti Mākino", "slug": "ngati-makino"},
  {"name": "Mohegan", "slug": "mohegan-2"},
  {"name": "Moses/Columbia", "slug": "moses-columbia"},
  {"name": "Ngāti Pāhauwera", "slug": "ngati-pahauwera"},
  {"name": "Saura", "slug": "saura"},
  {"name": "Bakanh", "slug": "bakanh"},
  {"name": "Saluda", "slug": "saluda"},
  {"name": "Ewe", "slug": "ewe"},
  {"name": "Ngāti Rehua", "slug": "ngati-rehua"},
  {"name": "Banjima", "slug": "banjima"},
  {"name": "np̓əšqʷáw̓səxʷ (Wenatchi)", "slug": "columbia-wenatchi"},
  {"name": "Ngāi Te Rangi", "slug": "ngai-te-rangi"},
  {"name": "šxʷməθkʷəy̓əmaɁɬ təməxʷ (Musqueam)", "slug": "xʷməθkʷəy̓əm"},
  {"name": "Macorix", "slug": "macorix"},
  {"name": "Poquonook", "slug": "poquonook"},
  {"name": "Oohenumpa", "slug": "oohenumpa"},
  {"name": "Djawi", "slug": "djawi"},
  {"name": "Eeyou Istchee", "slug": "cree-nehiawak-of-eeyou-istchee"},
  {"name": "Tekohá (Paĩ Tavytera/Kaiowá)", "slug": "tekoha-kaiowa"},
  {"name": "Anmatyerre", "slug": "anmatyerre"},
  {"name": "Koknar", "slug": "koknar"},
  {"name": "Kickapoo (Oklahoma)", "slug": "kickapoo-oklahoma"},
  {"name": "Itonama", "slug": "itonama"},
  {"name": "Muisca", "slug": "muisca"},
  {"name": "Perquimans", "slug": "perquimans"},
  {"name": "Heiltsuk", "slug": "heiltsuk"},
  {"name": "I'târap", "slug": "itarap"},
  {"name": "Guanaca", "slug": "guanaca"},
  {"name": "Canichana", "slug": "canichana"},
  {"name": "Ngarla", "slug": "ngarla"},
  {"name": "Tjalkanti", "slug": "tjalkanti"},
  {"name": "Wisijsa", "slug": "wisijsa"},
  {"name": "Ngāti Apa ki te Rā Tō", "slug": "ngati-apa-ki-te-ra-to"},
  {"name": "Ikpeng", "slug": "ikpeng"},
  {"name": "Ngumbarl", "slug": "ngumbarl"},
  {"name": "Chikashsha Yaki (Chickasaw)", "slug": "chickasaw"},
  {"name": "Nadöb", "slug": "nadob"},
  {"name": "Ngāti Tamaterā", "slug": "ngati-tamatera"},
  {"name": "Tsimane’", "slug": "tsimane"},
  {"name": "Umbindhamu", "slug": "umbindhamu"},
  {"name": "Ngāti Rangi", "slug": "ngati-rangi"},
  {"name": "Guna of Wargandí", "slug": "guna-of-wargandi"},
  {"name": "Cuchiyaga", "slug": "cuchiyaga"},
  {"name": "Lumnanas", "slug": "lumnanas"},
  {"name": "Ngandi", "slug": "ngandi"},
  {"name": "Te Patukirikiri", "slug": "te-patukirikiri"},
  {"name": "Champagne & Aishihik", "slug": "champagne-aishihik"},
  {"name": "Ngāti Awa", "slug": "ngati-awa"},
  {"name": "Cheyenne-Arapaho (Oklahoma)", "slug": "cheyenne-arapaho-oklahoma"},
  {"name": "Hopewell", "slug": "hopewell"},
  {
    "name": "Inikana/Kukama Kukamiria/Kokama",
    "slug": "inikana-kukama-kukamiria-kokama"
  },
  {"name": "Wayúu", "slug": "wayuu"},
  {"name": "Kullilla", "slug": "kullilla"},
  {"name": "Buandig", "slug": "buandig"},
  {"name": "Ngāti Tamaterā", "slug": "ngati-tamatera"},
  {"name": "Miyan", "slug": "miyan"},
  {"name": "So'to (Yekuana)", "slug": "soto-yekuana"},
  {"name": "Kamaiurá", "slug": "kamaiura"},
  {"name": "Yulparitja", "slug": "yulparitja"},
  {"name": "Meherrin", "slug": "meherrin"},
  {"name": "Jaminjung", "slug": "jaminjung"},
  {"name": "Esselen", "slug": "esselen"},
  {"name": "Ais", "slug": "ais-2"},
  {
    "name": "Seminole Tribe of Florida (Immokalee Reservation)",
    "slug": "seminole-tribe-of-florida-immokalee-reservation"
  },
  {"name": "Hul Kuhk’u", "slug": "hul-kuhku"},
  {"name": "Ngāti Apa ki te Rā Tō", "slug": "ngati-apa-ki-te-ra-to"},
  {"name": "Konnaack", "slug": "konnaack"},
  {
    "name": "Awaeté (Asurini of the Xingu)",
    "slug": "awaete-asurini-of-the-xingu"
  },
  {"name": "Multnomah", "slug": "multnomah"},
  {"name": "Ballardong", "slug": "ballardong"},
  {"name": "Karankawa", "slug": "karankawa-2"},
  {"name": "Kuthant", "slug": "kuthant"},
  {"name": "Hiaitsiihi", "slug": "hiaitsiihi"},
  {"name": "Barasano/Panenoá", "slug": "barasano-panenoa"},
  {"name": "Guajajara", "slug": "guajajara"},
  {"name": "Shakori", "slug": "shakori"},
  {"name": "Weenhayek/Wichí", "slug": "wichi"},
  {
    "name": "Carcross/Tagish First Nation (BC)",
    "slug": "carcross-tagish-first-nation-bc"
  },
  {"name": "Wonnarua", "slug": "wonnarua"},
  {"name": "Kuuku-yani", "slug": "kuuku-yani"},
  {
    "name": "Matlatzinco/Tlahuica/Ocuiltec",
    "slug": "matlatzincotlahuicaocuiltec"
  },
  {"name": "Nyawaygi", "slug": "nyawaygi"},
  {"name": "Barranbinya", "slug": "barranbinya"},
  {"name": "Hul'qumi'num Treaty Group", "slug": "hul-qumi-num-treaty-group"},
  {"name": "Mbya", "slug": "mbya"},
  {"name": "Kiriri", "slug": "kiriri"},
  {"name": "Corchaug", "slug": "corchaug"},
  {"name": "Ngāti Tama", "slug": "ngati-tama"},
  {"name": "Tumbalalá", "slug": "tumbalala"},
  {"name": "Ngan’giwumirri", "slug": "ngan-giwumirri"},
  {"name": "Teslin Tlingit Council (Yukon)", "slug": "teslin-tlingit"},
  {
    "name": "Potawatomi-Shawnee (Oklahoma)",
    "slug": "potawatomi-shawnee-oklahoma"
  },
  {"name": "Ket Chonhab’ Kob’a (Chuj)", "slug": "chuj"},
  {"name": "Épera", "slug": "epera"},
  {"name": "Yamayeka (Yamaye)", "slug": "yamayeka-yamaye"},
  {"name": "Choctaw (Oklahoma)", "slug": "choctaw-oklahoma"},
  {"name": "Ogiek", "slug": "ogiek"},
  {"name": "Ngāti Ranginui", "slug": "ngati-ranginui"},
  {"name": "Tūhoe", "slug": "tuhoe-2"},
  {"name": "Garingbal", "slug": "garingbal"},
  {"name": "Baraba Baraba", "slug": "baraba-baraba"},
  {"name": "Guwa", "slug": "guwa"},
  {"name": "Tampachoa (Mansos)", "slug": "mansos"},
  {"name": "Bia Mbyá", "slug": "bia-mbya"},
  {"name": "Te Patukirikiri", "slug": "te-patukirikiri"},
  {"name": "Tequesta", "slug": "tequesta"},
  {"name": "Panzaleo", "slug": "panzaleo"},
  {"name": "Beaver", "slug": "beaver"},
  {"name": "Toba-Lengua", "slug": "toba-lengua"},
  {"name": "Mechoopda", "slug": "mechoopda-maidu"},
  {"name": "Nyanganyatjara", "slug": "nyanganyatjara"},
  {"name": "Wuningangk", "slug": "wuningangk"},
  {"name": "Mohawk (Kalapuya)", "slug": "mohawk-4"},
  {"name": "Ngāti Whanaunga", "slug": "ngati-whanaunga"},
  {"name": "Cheroenhaka (Nottoway)", "slug": "cheroenhaka-nottoway"},
  {"name": "oθaakiiwaki‧hina‧ki (Sauk)", "slug": "oθaakiiwaki‧hina‧ki-sauk"},
  {"name": "Boriken Taino", "slug": "boriken-taino"},
  {"name": "Me-Wuk (Southern Sierra Miwok)", "slug": "southern-sierra-miwok"},
  {"name": "Secotan", "slug": "secotan"},
  {"name": "Gitga’at Lax Yuup", "slug": "gitgaat"},
  {"name": "Te Ākitai Waiohua", "slug": "te-akitai-waiohua"},
  {"name": "Pyemmairrener", "slug": "pyemmairrener"},
  {"name": "Gitga’at", "slug": "gitga-at"},
  {"name": "Nicoleño", "slug": "nicoleno"},
  {"name": "Tunumiit Nunaat", "slug": "tunumiit-oraasiat"},
  {"name": "Arosaguntacook", "slug": "arosaguntacook"},
  {"name": "Ahtna Nenn’", "slug": "ahtna"},
  {"name": "Janos", "slug": "janos"},
  {"name": "Ditidaht", "slug": "ditidaht"},
  {"name": "Danggali", "slug": "danggali"},
  {"name": "Awabakal", "slug": "awabakal"},
];
