const territoriesNames = [
  "Esketemculeucw (Esk'etemc)",
  "Coahuiltecan",
  "Matsés (Mayoruna)",
  "Caxcan",
  "ZioBain (Siona)",
  "Diaguita",
  "Wakabunga",
  "Muscogee (Oklahoma)",
  "Massawomeck",
  "Worimi",
  "Coyutecos (Nahua)",
  "Korubo",
  "Laklanõ",
  "Seminole Tribe of Florida (Brighton Reservation)",
  "Charrúa",
  "Kokomini",
  "Chilula",
  "Eastern Shoshone",
  "Runixa Ngiigua (Chocho)",
  "Margany",
  "Nonuya",
  "Ngāti Mutunga o Wharekauri (Chatham Islands)",
  "Bïde",
  "Gunbalang",
  "Atsugewi",
  "Cape Fear",
  "Chiricahua Apache",
  "Pamoari",
  "Assiniboine",
  "Secwepemcúl'ecw (Secwépemc)",
  "Kriol",
  "Mexicanero (Nahuas)",
  "Andoa",
  "Mosetén",
  "Queets",
  "Nungali",
  "Uspantec",
  "Entiat",
  "Nuwhaha",
  "Wangan",
  "Quuiich (Lower Umpqua)",
  "Ga",
  "Ngalakan",
  "E'ñepá",
  "Mirning",
  "Emberá Chamí",
  "Mayi-Kutuna",
  "Yindjibarndi",
  "Attiwonderonk (Neutral)",
  "Arabana",
  "Yoreme (Mayo)",
  "Nunggubuyu",
  "Chamicuro",
  "Yagán",
  "Sharanahua",
  "Kiliwa",
  "Guarijío/Guarijó",
  "Boonwurrung",
  "Sirionó",
  "Wyandotte (Oklahoma)",
  "Winaq Qo’ (Mam)",
  "Kichwa del Río Pastaza",
  "Tamaulipeco tribes",
  "Tzjon Non/ Tzo'tyio (Amuzgo)",
  "Günün a atük (Günün a küna)",
  "Yanda",
  "Mandandanji",
  "Ngāti Kahungunu ki Heretaunga Tamatea",
  "Bindjali",
  "Wakuenai/Walimanai (Kuripako)",
  "Tepehua",
  "Emberá",
  "Maniapoto",
  "Bilinara",
  "Ngāi Tai ki Tāmaki",
  "Lardil",
  "Ngāti Te Ata",
  "White River-Kluane",
  "Ngāti Pūkenga ki Waiau",
  "Siginygmit (Sireniki) Yupik",
  "Wabanaki (Dawnland Confederacy)",
  "Pacaxes",
  "Tjerratj",
  "Ucluelet",
  "Karajarri",
  "Modoc",
  "Darumbal",
  "Tekohá (Guarani)",
  "Limilngan",
  "Hesquiaht",
  "Havasu Baaja (Havasupai)",
  "Kalaamaya",
  "Muralag",
  "Shawi",
  "Nuxalk",
  "Gugu-Badhun",
  "Matecumbe",
  "Killaka Asanajaqi",
  "Huu-ay-aht",
  "Moraughtacund",
  "Ainu",
  "Kwikwetlem",
  "Ikolen",
  "Eperara Siapidara",
  "Kakataibo",
  "Kathlamet",
  "Ngāi Tai ki Tāmaki",
  "Angaité",
  "Wudjari",
  "Natabuela",
  "Nadleh Whut'en",
  "Yalarrnga",
  "Waiwai",
  "Ngāti Tamaoho",
  "Ashaninka",
  "San Carlos Apache",
  "Teslin Tlingit Council (BC)",
  "Sauk Suiattle",
  "Penobscot",
  "[Gáuigú (Kiowa)",
  "Northeastern Pomo",
  "Karkin",
  "Ayahuacas",
  "Mudburra",
  "Mi'kma'ki",
  "Kaingang",
  "Kawashkar",
  "Ngāti Maru (Hauraki)",
  "Matinecock",
  "Yitha Yitha",
  "Passamaquoddy",
  "Mbeiwum",
  "Magüta/Ticuna",
  "səl̓ilwətaɁɬ təməxʷ (Tsleil-Waututh)",
  "Aucocisco",
  "Zoró/Pangyjej",
  "Goreng",
  "Kantaruré",
  "Bostos",
  "Achagua",
  "Lingít Aaní (Tlingit)",
  "Gunwinggu",
  "Toogee",
  "Mayangna",
  "Canela Ramkokamekrá",
  "Wiradjuri",
  "Julimes",
  "Wulgurukaba",
  "Chimacum",
  "We Wai Kai",
  "Awá",
  "Arrernte",
  "Yadhaigana",
  "Kuuku-ya’u",
  "Mardu",
  "Xakriabá",
  "Nukini",
  "Enenlhet-Toba",
  "Yoko T’aan (Chontal)",
  "Konbudj",
  "Mánekenk/Haush",
  "Manahoac",
  "Whanganui Land Settlement (Lower Whanganui)",
  "Gayiri",
  "Sinkyone",
  "Kamëntsá",
  "Tastil",
  "Odǫhwęja:deˀ (Cayuga)",
  "Yinggarda",
  "Chapra",
  "Fernandeño Tataviam",
  "Ocloya",
  "Kelly Lake Metis Settlement Society",
  "Nunatsiavut",
  "Western Nehântick",
  "Ngāti Pikiao",
  "Nansemond",
  "Waxhaw",
  "Puyallup",
  "Nitaskinan (Atikamekw / Nehirowisi Aski)",
  "Me-Wuk (Coast Miwok)",
  "Moqoit",
  "Jamamadi",
  "Yidinjdji",
  "Ngāti Maru (Hauraki)",
  "Ngāti Hako",
  "Uru",
  "Yuwi",
  "Shíshálh",
  "Ngarinyin",
  "Luckiamute",
  "Tūhourangi",
  "Inughuit Nunaat",
  "Peramangk",
  "Ijku (Arhuaco)",
  "Nanrantsouak",
  "Garífuna",
  "Wangkamana",
  "Kichwa (Amazónico)",
  "Kambeba/Omagua",
  "Limuw",
  "Kogui/Kaggabba",
  "Tutelo",
  "Kallawaya",
  "Tagé Cho Hudän (Little Salmon/Carmacks)",
  "Atakapa-Ishak",
  "Ngāti Manuhiri",
  "Jococobas",
  "Doeg",
  "Amahuaca",
  "Bodéwadmiakiwen (Potawatomi)",
  "Klamath",
  "'Amuwu",
  "Sandawe",
  "Payómkawichum (Luiseño)",
  "Wagiman",
  "Me-Wuk (Bay Miwok)",
  "Mvskoke (Muscogee / Creek)",
  "Yupangathi",
  "Ngāti Pūkenga",
  "Paipai (Akwa'ala)",
  "Hia-Ced O'odham",
  "Tepehuán",
  "Ngāti Mutunga",
  "Ngāti Whare",
  "Te Korowai o Wainuiārua (Central Whanganui)",
  "Salasaka",
  "Mississaugas of the Credit First Nation",
  "Jarawara",
  "Somi Se'k (Esto’k Gna)",
  "Te Aitanga ā Māhaki",
  "Kisêdjê",
  "Nawa",
  "Jaqaru",
  "Ngāti Whanaunga",
  "Dhirari",
  "Gunadule (Kuna-Tule)",
  "Cession 362",
  "Warekena",
  "Xetá",
  "Yaminawá",
  "Guanahatabey",
  "Dokapuara (Tuyuca)",
  "Chontal de Guerrero – Tuxteco",
  "Maijuna",
  "Shigom",
  "Quillacinga",
  "Slijuala Xanuc (Chontal)",
  "Caddo",
  "Merrick",
  "Ngaanyatjarra",
  "komi voitõr",
  "Tapuika",
  "Erie",
  "Acho Dene Koe",
  "Djabuganjdji",
  "Tocobaga",
  "Ngāti Tahu / Ngāti Whaoa",
  "Geawegal",
  "Sanapaná",
  "Awajún",
  "Ngāti Toa Rangatira",
  "Kusso",
  "Osage (Oklahoma)",
  "Wôpanâak (Wampanoag)",
  "Turrbal",
  "Abitibiwinni Aki",
  "Kulina Pano",
  'Ye"pâ-masa',
  "Lower Tohono O’odham (Lower Pima)",
  "Kija",
  "Tsnungwe",
  "Nimanburu",
  "Garawa",
  "Sana",
  "Charka",
  "Mundurukânia (Wuy jugu)",
  "Akan",
  "Ngombur",
  "Alyawarre",
  "Ãwa",
  "Siuslaw",
  "NunatuKavut",
  "Kokatha",
  "Winda Winda",
  "Ngāti Maru (Hauraki)",
  "Qhara Qhara",
  "Djabwurung",
  "Kichwa",
  "Kojomk'awi (Konkow)",
  "Ka'apor",
  "Akimel O'odham (Upper Pima)",
  "Unggarangi",
  "Ngāti Maru (Hauraki)",
  "Nimiipuu (Nez Perce)",
  "Tonkawa (Oklahoma)",
  "Confederated Tribes of Grand Ronde",
  "Southeastern Pomo",
  "Kañari",
  "Ngāti Porou",
  "A'uwe",
  "Ohlone",
  "Chickahominy",
  "Chinantla (Tsa ju jmí’)",
  "Giya",
  "Zacateco ",
  "Nahua (Michoacan)",
  "Yazne",
  "Suquamish",
  "Gagudju",
  "Kunja",
  "Marubo",
  "Odawa",
  "Nauset",
  "Iwaidja",
  "Maung",
  "Nuwuvi (Southern Paiute)",
  "Ngāti Hei",
  "Nyamal",
  "Miluk Coos",
  "Warriyangga",
  "Yanga",
  "Marringarr",
  "Cayuse, Umatilla and Walla Walla",
  "Copuces",
  "Quinault",
  "Pakajaqi",
  "Southern Pomo",
  "Ngāti Maru (Hauraki)",
  "Tanigua",
  "Obispeño",
  "Wuli-wuli",
  "Ngarrindjeri",
  "Guató",
  "Bardi",
  "Skagit",
  "Whakatōhea",
  "Yambina",
  "Ngāpuhi",
  "Pech",
  "Ngāti Whanaunga",
  "Tłı̨chǫ Ndè",
  "Ngāti Whanaunga",
  "Chahta Yakni (Choctaw)",
  "Gananggalinda",
  "Yarluyandi",
  "Kurâ",
  "Cholulteca",
  "Yuru",
  "Wawula",
  "Kuyam",
  "Tecuexe",
  "Wyandot (Anderdon)",
  "Kiskiack",
  "Podunks",
  "Madija",
  "Aónikenk (Tehuelche)",
  "Ngāti Porou ki Harataunga ki Mataora",
  "Nyangumarda",
  "Eastern Mono/Monache",
  "Nissaquogue",
  "Wadi Wadi",
  "Khanty/Kantyk",
  "Sataré-Mawé",
  "Eastern Nehântick",
  "Guahibo/Hiwi",
  "Bibbulman",
  "Takla",
  "Aché",
  "Unangam Tanangin (Unangax̂ /Aleut)",
  "Ngāti Korokī Kahukura",
  "Ofaié",
  "Ts’uubaa-asatx",
  "Wappo",
  "Ngātiwai",
  "Biri",
  "Sobaipuri",
  "Kamilaroi",
  "Mojeño",
  "Mattaponi",
  "Piscataway",
  "Karjalaiset (Karelian)",
  "Dehcho Dene",
  "Monqui",
  "Gamberre",
  "Chankas",
  "Nasa",
  "Cuitlatec",
  "Shmuwich (Barbareño)",
  "Asheninka",
  "Wanano/Kotiria",
  "Ngatatjara",
  "Miccosukee",
  "Kumeyaay",
  "Ngāti Kahu",
  "Willapa",
  "Gungabula",
  "nuučaan̓uuɫɁatḥ nism̓a (Nuu-chah-nulth)",
  "Kaantju",
  "Acjachemen (Juaneño)",
  "Clatskanie",
  "Squaxin",
  "Warluwarra",
  "Yoncalla",
  "Moratok",
  "Ngāi Tai ki Tāmaki",
  "Kisii",
  "Wiyot",
  "Yankton",
  "Lenca",
  "Mayi-Yapi",
  "Sahtú Got’ine",
  "Ngamini",
  "Giraiwurung",
  "Biripi",
  "Umukomasã/Desana",
  "Ngāti Manuhiri",
  "Chehalis",
  "Appamattuck",
  "U'wa",
  "Karenggapa",
  "Swinomish",
  "BOḰEĆEN (Pauquachin)",
  "Onawmanient",
  "Bigambul",
  "Clackamas",
  "Cuica",
  "Tomabela",
  "Parkatejê",
  "Menominee",
  "Chalon",
  "Neusiok",
  "Agwarmin",
  "Vanyumé",
  "Matsigenka",
  "Tanacross",
  "Warwa",
  "Cherokee (Oklahoma)",
  "Lucayo",
  "Salmon River",
  "Cahto",
  "Kayambi",
  "Croatan",
  "Ngāti Apa ki te Rā Tō",
  "Te Patukirikiri",
  "Enawenê-nawê",
  "Maańśi",
  "Ngāti Rangiteaorere",
  "Quw'utsun",
  "Rikbaktsá",
  "Pueblos",
  "Nambikwara",
  "Gayardilt",
  "Yangga",
  "Ngāi Tahu",
  "Wasco and Wishram",
  "Quandamooka",
  "Kaimbé",
  "Te Patukirikiri",
  "Pamlico (Pomouik)",
  "Tāłtān Konelīne (Tahltan)",
  "Wemba Wemba",
  "Canela Apanyekrá",
  "Kitasoo/Xai'xais",
  "Nükak Makü",
  "Tetlit Gwich’in",
  "Alawa",
  "Chelamela",
  "Mannansett",
  "Te Patukirikiri",
  "Anambé",
  "Halíti",
  "Xinca",
  "Ngāi Tai ki Tāmaki",
  "Tulalip",
  "Waípinõmakã (Bará)",
  "Matetamãe/Cinta Larga",
  "Cow Creek Umpqua",
  "Arara of Volta Grande",
  "Tigua",
  "Wateree",
  "Yuin",
  "Waveroo",
  "Te Patukirikiri",
  "Bayali",
  "Yangman",
  "Tillamook",
  "Ngāi Tai ki Tāmaki",
  "Kitanemuk",
  "Gunditjmara",
  "Taos Pueblo",
  "Nunavik",
  "Sac and Fox (Oklahoma)",
  "Sahtu Dene and Metis",
  "Wirangu",
  "Sanavirones",
  "Budjari",
  "Apiaká",
  "Palouse",
  "Tenetehara (Tembé)",
  "Kalapalo",
  "Ngawun",
  "Tanana",
  "ɬaʔamɩn gɩǰɛ (Tla'amin/Sliammon)",
  "Confederated Tribes of Siletz Indians",
  "Parikwene",
  "Pit River",
  "Arapaho",
  "Ngāti Rehua",
  "Barunggam",
  "Baradha",
  "Hupd'äh",
  "Wari’",
  "Waitaha",
  "Skwxwú7mesh-ulh Temíx̱w (Squamish)",
  "Taranaki Whānui ki te Upoko o te Ika",
  "Tjungundji",
  "S’ólh Téméxw (Stó:lō)",
  "Timotes",
  "Lower Chinook",
  "Gitxaała",
  "Ngāti Tamaoho",
  "Yaruro/Pumé",
  "Movima",
  "Inuvialuit",
  "Musgamagw Dzawada'enuxw",
  "Muwekma",
  "Uchucklesaht",
  "Dënéndeh",
  "Dieri",
  "Kwini",
  "Waranka",
  "Waikato",
  "Mutumui",
  "Walangama",
  "Apyãwa",
  "Werowocomoco",
  "Kisapincha",
  "Mazahua",
  "Chochenyo",
  "Jardwadjali",
  "Homalco",
  "Kamejeya (Yukuna)",
  "Setauket",
  "Nom Sus Wintu",
  "Salish Kootenai (Flathead)",
  "Wik",
  "Sicangu",
  "Mount Tabor Indian Community",
  "Guugu-Yimidhirr",
  "Calicuas",
  "Patwin",
  "Wahkiakum",
  "Tenino",
  "Tontotuna (Totoró)",
  "Michumash",
  "Coree",
  "K’áálǫ Got’ine",
  "Mebêngôkre (Kayapó)",
  "Beaver",
  "Ngātiwai",
  "Molalla",
  "Wichita-Caddo-Delaware (Oklahoma)",
  "Sumas",
  "Djeoromitxí",
  "Maká",
  "Lickanantay",
  "Kizh",
  "Muaūpoko",
  "Sappony",
  "Tapieté/Guaraní-Ñandeva",
  "Kashaya",
  "Bohanes",
  "Peoria (Oklahoma)",
  "Ngarabal",
  "Wichita",
  "Anggamudi",
  "Myaamia",
  "Aikanã",
  "Wari",
  "Catawba",
  "Poqomam",
  "Luthigh",
  "Pitta-Pitta",
  "Montaukett",
  "Dau Pom Wintu",
  "No'iria",
  "Djargurdwurung",
  "Kala Lagaw Ya",
  "Karijona",
  "Eyak",
  "Huaylas",
  "Onʌyote'a•ka (Oneida)",
  "Pentucket",
  "Narangga",
  "Pokanoket",
  "Timucua",
  "Larrakia",
  "Makah",
  "Amangu",
  "Yeopim",
  "Canarsie",
  "Selk'nam",
  "Cuicuilco",
  "Á,LEṈENEȻ ȽTE (W̱SÁNEĆ)",
  "Deni",
  "Gulidjan",
  "Cheraw",
  "Kichwa Santarrosino",
  "Tsase/Piapoco",
  "Ngāi Tai ki Tāmaki",
  "Baure",
  "Paugussett",
  "Yanyuwa",
  "Takalak",
  "Ngāti Tara Tokanui",
  "Haida Gwaii",
  "Patamona/Ingarikó",
  "Barkindji",
  "Cahuilla",
  "Chickasaw (Oklahoma)",
  "Thalanyji",
  "Ngāti Whanaunga",
  "Kitu Kara",
  "Achí",
  "Ngadjuri",
  "Goshute",
  "Gungurugoni",
  "Amboca",
  "Ngaliwuru",
  "Moriori",
  "Ngātiwai",
  "Qayqayt",
  "Massacoes",
  "Cheyenne",
  "Houma",
  "Pitjantjatjara",
  "Woolna",
  "Ngatjumay",
  "Kaiabi",
  "Big Stone Cree",
  "Gwich'in Nành",
  "Vacacocha",
  "Murrinh-patha",
  "Seminole (Oklahoma)",
  "Lamalama",
  "Inkeriläinen",
  "Winnimem Wintu",
  "Kluane",
  "Yandruwandha",
  "Rembarnga",
  "Tanimuka",
  "Taku River Tlingit",
  "Pijao",
  "Siekopa’aiInte/Aido-Pãi (Secoya)",
  "Kitselas",
  "Manoki",
  "Mokaná",
  "Yugambeh",
  "Ngāti Paoa",
  "Kuuvuan KaNianiq",
  "Ayoreo",
  "Wolastoqiyik Wahsipekuk (Maliseet)",
  "Kankuamo",
  "Kundjey’mi",
  "Makurap",
  "Paltas",
  "Enlhet",
  "Dena'ina Ełnena",
  "Añuu",
  "Wardandi",
  "Unkechaug",
  "Araona",
  "Pescado",
  "Minang",
  "Nʉmʉnʉʉ (Comanche)",
  "Umida",
  "Massapequas",
  "Malyangaba",
  "Mescalero Apache",
  "Marinahua",
  "Dakeł Keyoh (ᑕᗸᒡ ᗲᘏᑋ)",
  "Resígaro",
  "Kurnai",
  "Hixkaryana",
  "Ngāti Maru (Hauraki)",
  "Mississauga",
  "Ch'orti'",
  "Kichwa del Río Napo",
  "Pisamira",
  "Xixime",
  "Waíkhana",
  "Hñähñu (Otomí)",
  "Amarak",
  "KiKiallus",
  "Pâri (Pawnee)",
  "Yaros",
  "Söl'kup",
  "Watjarri",
  "Dharug",
  "Qwû'lh-hwai-pûm (Klickitat)",
  "Wappinger",
  "Chitimacha",
  "Raukawa",
  "Congaree",
  "Trio/Wü tarëno",
  "Kokowarra",
  "Modoc (Oklahoma)",
  "Nor Rel Muk Wintu",
  "Ngāti Rongomai",
  "Wangunks",
  "N’eney N’enet’s’ (Nenets)",
  "Yukpa",
  "Jupaú (Kawahib)",
  "Ulwas",
  "Trumai",
  "Ngāti Hineuru",
  "Ngāti Rārua",
  "Rapa Nui",
  "Nomatsigenga",
  "Te Kawerau a Maki",
  "Ngāti Paoa",
  "Pawnee (Oklahoma)",
  "Yamhill",
  "Moneton",
  "O-ga-xpa Ma-zhoⁿ (O-ga-xpa)",
  "Palyku",
  "Tommeginne",
  "Bidai",
  "Ngarti",
  "Huasteco/Teenek",
  "Northern Pomo",
  "Lassik",
  "Ngāti Whanaunga",
  "Mountain Maidu",
  "Chukchansi",
  "Mochó",
  "Thul Garrie Waja (Bindal)",
  "Waazija (Ho-Chunk / Winnebago)",
  "Wathaurong",
  "Eastern Shawnee (Oklahoma)",
  "Kaska Dena Kayeh",
  "Pirlatapa",
  "Kurtjar",
  "Baré",
  "Vuntut Gwitchin",
  "Wiilman",
  "Omàmìwininìwag (Algonquin)",
  "Pankará",
  "Newe (Western Shoshone)",
  "Pocomoke",
  "Cochimí",
  "Adena",
  "Yihamwo (Yagua)",
  "Ngāti Kuia",
  "Rangitāne",
  "Kawahib (Parintintin)",
  "Deg Xit'an Ngan' (Deg Xit'an)",
  "Dangbon",
  "Pinjarup",
  "Kukatj",
  "Chowanoke",
  "Winefelly",
  "Tŝilhqot’in Nen",
  "Kwazá",
  "Yine",
  "Ecuana",
  "Ngāpuhi",
  "Wuthathi",
  "Misak",
  "Ngāti Hauiti",
  "Yurutí",
  "Tagish",
  "Warao",
  "Pascua Yaqui",
  "Banawá",
  "Paspahegh",
  "Akaitcho",
  "Te Aupōuri",
  "Hualapai",
  "Mnicoujou",
  "Te Uri o Hau",
  "Denendeh (Dënësųłinë́ Nëné)",
  "Yolngu",
  "Wicocomico",
  "W̱SĺḴEM (Tseycum)",
  "Nuenonne",
  "Te’mexw Treaty Association",
  "Leco",
  "Kadiwéu",
  "Skykomish",
  "Kashtik ",
  "Great Lakes Twa",
  "Moose Cree",
  "Ngāti Ruanui",
  "Ngāti Rangiwewehi",
  "Kwantlen",
  "Chimariko (territory)",
  "Sakurabiat",
  "Matagalpa/Cacaopera",
  "Stz'uminus",
  "Seminole Tribe of Florida (Tampa Reservation)",
  "Bora",
  "Maya Yucateco",
  "Lokono (Arawak)",
  "Wardaman",
  "Umurecoómajá (Tatuyo)",
  "Sekakawon",
  "Ngāti Kuri",
  "Ngāti Maru (Taranaki)",
  "Wendake-Nionwentsïo",
  "Weyanock",
  "Dagomba",
  "Awaswas",
  "Ngāti Tamaterā",
  "Karajá do Norte",
  "Abenaki / Abénaquis",
  "WiYaPeMiAk (Weapemeoc-Yeopim)",
  "Zo’é",
  "Kalapuya",
  "Nanti",
  "Bribri",
  "Konomihu",
  "Ngāti Tara Tokanui",
  "Warray",
  "Jurruru",
  "Peerapper",
  "Chimú",
  "Núu-agha-tʉvʉ-pʉ̱ (Ute)",
  "Hohokam",
  "Pequawket",
  "Tuscarora",
  "Ngāti Toa Rangatira",
  "Kukatja",
  "Kalaw Kawaw Ya",
  "Taino",
  "Iningai",
  "Lheidli T'enneh",
  "Huetar",
  "Pocumtuc",
  "WiYaPeMiAk (Weapemeoc-Yeopim)",
  "Wiljali",
  "Wangkangurru",
  "Kakinte",
  "Matlatzinco/matlatzinteca",
  "Tuxá",
  "Rankülche",
  "Tolupan",
  "Te Wairoa iwi and hapu",
  "Guarayo",
  "Occaneechi",
  "Lekwungen/Songhees",
  "Suruwaha",
  "Huarpe",
  "Nahua ( Morelos, Puebla, Tlaxcala, Veracruz, Hidalgo, San Luis Potosi)",
  "Wanapum",
  "Latje Latje",
  "Yana",
  "Seminole Tribe of Florida (Hollywood Reservation)",
  "Mingin",
  "Me-Wuk (Central Sierra Miwok)",
  "Central Pomo",
  "Wallmapu (Mapuche)",
  "Ngāi Tai ki Tāmaki",
  "Älsé (Alsea)",
  "Bidwell",
  "Yagalingu",
  "Purduna",
  "Tyerrernotepanner",
  "Očhéthi Šakówiŋ",
  "Muniche",
  "Gundungurra",
  "Koko-bera",
  "NWT Métis Nation",
  "Vepslaine/Vepsalne (Veps)",
  "Ngāti Maru (Hauraki)",
  "Ngāti Rāhiri Tumutumu",
  "Rangitāne o Wairau",
  "Sturgeon Lake Cree",
  "Ngāti Kea / Ngāti Tuarā",
  "Aseniwuche Winewak (Rocky Mountain)",
  "Whilkut",
  "Pintupi",
  "Winyah",
  "Ngāti Tamaterā",
  "Yurí",
  "Tawahka",
  "Keyauwee",
  "Ngāti Mutunga o Wharekauri (Chatham Islands)",
  "Emberá Dobidá",
  "Ngargad",
  "Envuga (Kawahib)",
  "Ahé (Kawahib)",
  "Chiso",
  "Ngāitai (Bay Of Plenty)",
  "Te Patukirikiri",
  "Djirbalngan",
  "Tharawal",
  "Kubéwa/Cubeo",
  "Ngāi Tai ki Tāmaki",
  "Gurindji",
  "Awytyza",
  "Miwa",
  "Chichas",
  "Guwinmal",
  "Ngāti Kahu ki Whangaroa",
  "Nuxwsa'7aq (Nooksack)",
  "Itazipco",
  "Yanam (Ninam)",
  "Kuwema",
  "Onundagaonoga (Onondaga)",
  "Marrithiyel",
  "Te Atiawa ki Whakarongotai",
  "Ngāti Whanaunga",
  "Ngāti Mākino",
  "Mohegan",
  "Moses/Columbia",
  "Ngāti Pāhauwera",
  "Saura",
  "Bakanh",
  "Saluda",
  "Ewe",
  "Ngāti Rehua",
  "Banjima",
  "np̓əšqʷáw̓səxʷ (Wenatchi)",
  "Ngāi Te Rangi",
  "šxʷməθkʷəy̓əmaɁɬ təməxʷ (Musqueam)",
  "Macorix",
  "Poquonook",
  "Oohenumpa",
  "Djawi",
  "Eeyou Istchee",
  "Tekohá (Paĩ Tavytera/Kaiowá)",
  "Anmatyerre",
  "Koknar",
  "Kickapoo (Oklahoma)",
  "Itonama",
  "Muisca",
  "Perquimans",
  "Heiltsuk",
  "I'târap",
  "Guanaca",
  "Canichana",
  "Ngarla",
  "Tjalkanti",
  "Wisijsa",
  "Ngāti Apa ki te Rā Tō",
  "Ikpeng",
  "Ngumbarl",
  "Chikashsha Yaki (Chickasaw)",
  "Nadöb",
  "Ngāti Tamaterā",
  "Tsimane’",
  "Umbindhamu",
  "Ngāti Rangi",
  "Guna of Wargandí",
  "Cuchiyaga",
  "Lumnanas",
  "Ngandi",
  "Te Patukirikiri",
  "Champagne & Aishihik",
  "Ngāti Awa",
  "Cheyenne-Arapaho (Oklahoma)",
  "Hopewell",
  "Inikana/Kukama Kukamiria/Kokama",
  "Wayúu",
  "Kullilla",
  "Buandig",
  "Ngāti Tamaterā",
  "Miyan",
  "So'to (Yekuana)",
  "Kamaiurá",
  "Yulparitja",
  "Meherrin",
  "Jaminjung",
  "Esselen",
  "Ais",
  "Seminole Tribe of Florida (Immokalee Reservation)",
  "Hul Kuhk’u",
  "Ngāti Apa ki te Rā Tō",
  "Konnaack",
  "Awaeté (Asurini of the Xingu)",
  "Multnomah",
  "Ballardong",
  "Karankawa",
  "Kuthant",
  "Hiaitsiihi",
  "Barasano/Panenoá",
  "Guajajara",
  "Shakori",
  "Weenhayek/Wichí",
  "Carcross/Tagish First Nation (BC)",
  "Wonnarua",
  "Kuuku-yani",
  "Matlatzinco/Tlahuica/Ocuiltec",
  "Nyawaygi",
  "Barranbinya",
  "Hul'qumi'num Treaty Group",
  "Mbya",
  "Kiriri",
  "Corchaug",
  "Ngāti Tama",
  "Tumbalalá",
  "Ngan’giwumirri",
  "Teslin Tlingit Council (Yukon)",
  "Potawatomi-Shawnee (Oklahoma)",
  "Ket Chonhab’ Kob’a (Chuj)",
  "Épera",
  "Yamayeka (Yamaye)",
  "Choctaw (Oklahoma)",
  "Ogiek",
  "Ngāti Ranginui",
  "Tūhoe",
  "Garingbal",
  "Baraba Baraba",
  "Guwa",
  "Tampachoa (Mansos)",
  "Bia Mbyá",
  "Te Patukirikiri",
  "Tequesta",
  "Panzaleo",
  "Beaver",
  "Toba-Lengua",
  "Mechoopda",
  "Nyanganyatjara",
  "Wuningangk",
  "Mohawk (Kalapuya)",
  "Ngāti Whanaunga",
  "Cheroenhaka (Nottoway)",
  "oθaakiiwaki‧hina‧ki (Sauk)",
  "Boriken Taino",
  "Me-Wuk (Southern Sierra Miwok)",
  "Secotan",
  "Gitga’at Lax Yuup",
  "Te Ākitai Waiohua",
  "Pyemmairrener",
  "Gitga’at",
  "Nicoleño",
  "Tunumiit Nunaat",
  "Arosaguntacook",
  "Ahtna Nenn’",
  "Janos",
  "Ditidaht",
  "Danggali",
  "Awabakal",
];
